### ISSUE TITLE
Plugins: Cleanup plugin will leave 'beauty' rendered files

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#1134]
**Bug**

Publishing multiple instances on farm from Maya - for example `Main` (beauty), `Shadows`, and `Normals` will finish and cleanup plugin should delete all after they are copied to their final destination. It will delete `Shadows` and `Normals` but leave `Main` behind.

[cuID:PYPE-1154]

**Comment by mkolar** [comment]
@antirotor I believe this was recently fixed on client site wasn't it?
