### ISSUE TITLE
Maya: Renderman support issues

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#1361]
## RenderMan issues

Currently limited support for RenderMan in Maya is having these problems:

- [ ] Creator won't set proper Render Settings
- [X] Render settings validator is validating wrong attributes for image prefix (`imageFileFormat` only, but it should check `imageOutputDirectory` __AND__ `imageFileFormat`) (Solved by #3006)
- [ ] Enabling animation in 🔼 validator repair action
- [ ] Publishing/Loading RIB files?

[cuID:PYPE-1348]

**Comment by mkolar** [comment]
@antirotor are these still a thing considering we're bashing shots our in renderman in production?

**Comment by antirotor** [comment]
> @antirotor are these still a thing considering we're bashing shots our in renderman in production?

Those unchecked boxes are still unaddressed and I consider them important to call that we have full support for Renderman (well perhaps minus the rib file publishing, but instead of it we can add support for renderman optimized textures). So to fullfill it I would at least address **Creator won't set proper Render Settings** and **Enabling animation in 🔼 validator repair action**
