### ISSUE TITLE
Nuke: improve containerisation

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#1567]
## Description
At the moment if multiple nodes are loaded to script there is now way to correctly update them to new version as the container metadata are only kept on Read node. 

So for example when Retime and Timewarp is published out of Hiero. Those are loaded as thow additional nodes under Read node. 

## Solution
Add all nodes to Group  -  the same as Write nodes. Update would be easyer as we would just replace the group node. 

[cuID:PYPE-1325]

**Comment by tokejepsen** [comment]
This should be easier if the upstream Nuke workflow was ingested.

**Comment by jakubjezek001** [comment]
This had been implemented via https://github.com/ynput/OpenPype/pull/2128 with the use of `set_member` with `container_id` knob attribute.
