### ISSUE TITLE
Maya: support for compressed Maya Ascii scene files

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#1666]
## Feature

 Currently OpenPype doesn't support `.ma.gz` scene type files. Also we don't validate scene settings so if such type shows up it crash the integrator.

[cuID:PYPE-1333]

**Comment by BigRoy** [comment]
How does this Maya feature work on Windows? 

I've set the following:
- `Windows > Settings/Preferences > Preferences`
- `Settings > Files/Projects > Ascii File Compression Mode` set to **Compressed**

During saving without `gzip.exe` on `PATH` I get this warning/error in script editor: 
```// Error: Cannot locate gzip.exe.  File saved uncompressed. // ```


I've tried finding binaries for `gzip.exe` but binaries apparently haven't been recently put out there anymore? 
I've found this list of releases (dating 2017): https://sourceforge.net/projects/gnuwin32/files/gzip/
With that `gzip.exe` on my `PATH` I'm not getting the error anymore in my script editor and the script editor logs this:
```
// Result: C:/path/to/file.ma.gz // 
```
However on disk there's no `.ma.gz` file but only the `.ma` one without `.gz` suffix when I save as `.ma` in the browser.
If I save in the browser to `.ma.gz` directly it does name the file like that but the file is basically saved as regular `.ma` without compression, just named `.ma.gz`

It looks like the gzip version from 2017 isn't compatible and maya doesn't show it's failing with any error whatsoever.

### Related

- [Maya TroubleShooting: How to set up gzip compression](https://knowledge.autodesk.com/support/maya/troubleshooting/caas/sfdcarticles/sfdcarticles/Error-Cannot-locate-gzip-exe-File-saved-uncompressed-in-Maya-and-Maya-LT-2018-and-earlier-versions.html)
- There are much more recent version os gzip source code, but I see no pre-built binaries I can download on the [gzip website](https://www.gzip.org/). Latest sources found [here](https://ftp.gnu.org/gnu/gzip/?C=M;O=D) currently dating 2021-09-03 10:39.

**Comment by antirotor** [comment]
I think this doesn't work at all on WIndows and even Maya doesn't offer it so this feature is not viable on multiplatform studio setup. But if you are only linux based, it makes sense.

**Comment by antirotor** [comment]
Closing this issue for lack of traction. Feel free to reopen it when needed.
