### ISSUE TITLE
Single definition of host name for publishing

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/OpenPype#1730]
## Description
We don't have a way how to get a host name. Currently is used environment `AVLON_APP` which should hold host name to be used but it would be great if we would have a collector or a function to get it at any time the same way.

[cuID:yjxych]

**Comment by BigRoy** [comment]
@iLLiCiTiT it seems this has been solved with this [CollectHostName](https://github.com/ynput/OpenPype/blob/develop/openpype/plugins/publish/collect_host_name.py) plug-in?

**Comment by iLLiCiTiT** [comment]
I think https://github.com/ynput/OpenPype/pull/4723 will resolve this for 99%

**Comment by BigRoy** [comment]
Sounds good. Then we can link this up to auto-close if that gets merged?
