### ISSUE TITLE
`ProcessSubmittedJobOnFarm` Plulgin refactory

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#1820]
**Is your feature request related to a problem? Please describe.**
At the moment this plugin is holding multiple module specific code. So for example Deadline and Muster code are part of one plugin.

**Describe the solution you'd like**
Separate modul specific into separate plugins so those could be controlled with settings.

[cuID:[OP-1147](https://app.clickup.com/t/yjxzk5)]

**Comment by jezscha** [comment]
at the moment the plugin is living under deadline module, but practically it is Global plugin. `openpype\modules\deadline\plugins\publish\submit_publish_job.py`

**Comment by BigRoy** [comment]
With this now separated out to `ayon-deadline` in AYON I'm pretty sure this is solved in AYON. If not, we'll definitely be facing issues with Muster there down the line in what is then a dedicated muster integration. Closing this for OpenPype as not being relevant anymore?
