### ISSUE TITLE
Client: burnin new features

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#1831]
closes https://github.com/pypeclub/client/issues/96

- [ ] different font style per region 
- [ ] background rectangle shape over full width
- [ ] support for multiple lines in case of Comments (client feedback)
- [ ] image as logo in region (png with alpha)

[cuID:PYPE-1309]

**Comment by BigRoy** [comment]
This appears to be an old issue with a few tasks with a high severity. Are any of these tasks completed? :)

The link to the old issue isn't accessible to me could you elaborate on the "background rectangle shape over full width" - how do you envision this working? Would it be like a height/width percentage they'd define to add a half transparent box?

>  support for multiple lines in case of Comments (client feedback)

Like auto-wrapping based on some width?

**Comment by jakubjezek001** [comment]
I believe this is already solved by Premium burning add-on. But lets @iLLiCiTiT confirm this.

**Comment by jakubjezek001** [comment]
so confirmed. this had been implemented already
