### ISSUE TITLE
External addons central studio repository

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#2005]
**Is your feature request related to a problem? Please describe.**
At this moment of MVP for addons we are not considering fact that in case of multiplatform studio environment the central repository for addons would develop sever clashes. PYC created in windows might not be acepted with macos or linux distros. 

**Describe the solution you'd like**
Some sort of user's localisation should be developed or a way of running python scripts without cashing binaries. 

[cuID:[OP-1633](https://app.clickup.com/t/1259c0z)]

**Comment by mkolar** [comment]
This is being designed as part of the addon system in v4 and is on v4 backlog already. I will close this
