### ISSUE TITLE
Standalone sanity/repair interface

### ISSUE THREAD

**Issue by jlorrain** [ynput/OpenPype#2112]
Actually, an artist need to run all the sanity at once within pyblish.

In our current workflow, artists are used to often run sanity and repair their scene when they are working
(e.g. quickly check 0 transforms on their last modifications and fix them if necessary).

This would be really useful to have an interface which allows the artist to only run specified sanity on the current scene without the need to collect all the unnecessary information (like pyblish does at the moment).

#### Why
To allow the artist to efficiently check and repair a specific thing in his scene.

#### How
We could have a "Sanity mode" checkbox button in the pyblish interface that would **remove** the Extractors and Integrators plugins and Make all the Validators plugins has **optional** and would deactivate all of them.
The artist could then select the Validators of his choice and run them.
Within this mode The pyblish interface would have to **remember** the activated Validators so that the artist could quickly re-run them without the need to select them again

#### Why
In extension to the first feature, to save some time at runtime.

#### How
?

[cuID:OP-1810]

**Comment by mkolar** [comment]
This is somewhat achievable even now, albeit it is not exactly smooth sailing and the idea presented here is not bad at all. At the moment there are validator filters in the publish GUI in the top right, that can be set to turn on and off any optional validators. If you made all validator optional by default in the settings this could be used to achieve quick filtering. Secondly there is `validate` button in the GUI that only runs the validations. It's a poor man version, but could get you a long way for now. 

It's worth looking at dedicated validate/repair GUi that would make it all easier though.

**Comment by jlorrain** [comment]
> If you made all validator optional by default in the settings this could be used to achieve quick filtering

We don't want to lose this feature when publishing. The goal is to either partially validate the scene the way the artist want without being able to publish it, or publish the scene cleanly within the pipeline.
