### ISSUE TITLE
Maya: dirmap and multiroot

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#2123]
`dirmap` in Maya should take into account multiroot settings of OpenPype.

[cuID:1md0vr6]

**Comment by mkolar** [comment]
I believe it already does and it's being used in production, doesn't it?

**Comment by BigRoy** [comment]
I believe it is yes - it's implemented [here](https://github.com/pypeclub/OpenPype/blob/a579cd31c8974b36eddb1062b1d582282420e272/openpype/hosts/maya/api/pipeline.py#L53-L54) on Maya host install.

**Comment by tokejepsen** [comment]
Closing this as its implemented.
