### ISSUE TITLE
Standalone publisher editorial adding event order

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#2213]
**Is your feature request related to a problem? Please describe.**
At the moment we are not able to deal with multiple occurrences of a clip name. I a name is detected multiply exception will raise an error.

**Describe the solution you'd like**
We could deploi an enhencement to renamer to add an order number in case there are multiple ocurances of the same name. The number will be based on a possition of clip on timeline. New token for name template will be created `{clip_order:02d}`. It will be usually holding number `1` but in case of multiple clip name detection it will create a sequence.

**Describe alternatives you've considered**
We could also create `{clip_index:03d}`. It will add number to every clip based on position on timeline. Disadvantage would be in case of need for republishing a new cut of editorial, wchich might be a case of regular problem. 

**Additional context**
- clients are usually doing many publishes of the same edl/xml during a project life. 
- sometimes they only need to generate shot names on full clip name + some unification token in case of mulple occurancies of the same clip name. 

[cuID:[OP-1979](https://app.clickup.com/t/1r55uuy)]

**Comment by mkolar** [comment]
I'll take the libery of closing this. 3 years old seems stale enough.
