### ISSUE TITLE
Maya: Missing PyMEL issue

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#2353]
## Problem

Some of publishing plugins are not working in Maya 2022 because of missing pymel module:

```
Skipped: "%s" (%s) collect_ass No module named 'pymel'
Skipped: "%s" (%s) collect_renderable_camera No module named 'pymel'
Skipped: "%s" (%s) collect_review No module named 'pymel'
Skipped: "%s" (%s) extract_playblast No module named 'pymel'
Skipped: "%s" (%s) extract_thumbnail No module named 'pymel'
Skipped: "%s" (%s) validate_attributes No module named 'pymel'
Skipped: "%s" (%s) validate_mesh_arnold_attributes No module named 'pymel'
Skipped: "%s" (%s) validate_mesh_overlapping_uvs No module named 'pymel'
Skipped: "%s" (%s) validate_no_namespace No module named 'pymel'
Skipped: "%s" (%s) validate_render_image_rule No module named 'pymel'
Skipped: "%s" (%s) validate_rig_output_ids No module named 'pymel'
```

PyMel is can be missing from Maya (can be installed separately) and we should account for that.

It can be installed like `mayapy -m pip install pymel` or `mayapy -m pip install --user pymel`

We should use Validator to find out if we have pymel available and instruct user to install it, or we should do it automatically (tricky, because it will either neeed Administrator privilegues as it will modify maya install location, or it will install per user)

[cuID:OP-2084]

**Comment by BigRoy** [comment]
Without Pymel the user is also unable to e.g. load a published model - resulting in an error like this:
![maya_load_model_no_pymel](https://user-images.githubusercontent.com/2439881/146188533-21bef1ed-d40b-4bde-9d91-bc874c1a8900.png)

**Comment by BigRoy** [comment]
> We should use Validator to find out if we have pymel available and instruct user to install it, or we should do it automatically (tricky, because it will either neeed Administrator privilegues as it will modify maya install location, or it will install per user)

That wouldn't be the case if just provide the `pymel` package as a dependency to OpenPype however. Nevertheless, the easier fix might be to not reply on Pymel altogether.

**Comment by ClementHector** [comment]
We can verify / solve this problem in several places:
  - In the launcher, check with `mayapy pip seach mayapy`
  - When starting maya, check with `import pymel`
  - In pyblish, check with a pyblish plugin and a resolver

**Comment by ClementHector** [comment]
> That wouldn't be the case if we just provide the `pymel` package as a dependency to OpenPype however. Nevertheless, the easier fix might be to not reply on Pymel altogether.

I am afraid that this may not be possible because some future version of pymel may not work with maya 2022 and pymel which must install by mayapy.

**Comment by BigRoy** [comment]
> I am afraid that this may not be possible because some future version of pymel may not work with maya 2022 and pymel which must install by mayapy.

True. We would likely need a pymel version per Maya version in that case.

Anyway, might also be able to just ["find" the package](https://stackoverflow.com/a/14050282) without importing it as 'validation' on launch so that Pymel doesn't necessarily try to to initialize.

**Comment by ClementHector** [comment]
> Anyway, might also be able to just ["find" the package](https://stackoverflow.com/a/14050282) without importing it as 'validation' on launch so that Pymel doesn't necessarily try to to initialize.

good idea!

**Comment by BigRoy** [comment]
The Pymel issue itself isn't fixed with #2445. Machines can still have missing Pymel and get the same 'error'. Just to be aware of.

**Comment by mkolar** [comment]
true. I'm reopening this so we don't forget and remaining to Maya in general. not just 2022

**Comment by m-u-r-p-h-y** [comment]
just bumping the issue as we came across the missing pymel install on some client machine again . . .
