### ISSUE TITLE
Maya: Keep selection handle consistent to geometry updates

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#2444]
**Is your feature request related to a problem? Please describe.**

Loading a published Alembic loads (by default) with the Selection Handle enabled. Upon first load Maya centers this based on the bounding box of the geometry.

However, upon updating the versions of the loaded content the handle doesn't recenter. Which means that if the updated content is very different in size or even moved in location than the Selection Handle isn't consistent with the new location.

**Describe the solution you'd like**

To ensure consistency we should either:
- Update Selection Handle to the new (local space) center after updating the geometry.
```python
import maya.api.OpenMaya as om
from maya import cmds
    
def get_local_center(dag_node):
    
    # The bounding box of a transform is always returned in world
    # space even with the `objectSpace` flag - that only works on meshes
    # directly. So we just make the bounds local space ourselves.
    bounds = cmds.xform(dag_node, query=True, worldSpace=True, boundingBox=True)
    
    bmin = om.MPoint(bounds[:3])
    bmax = om.MPoint(bounds[3:])
    matrix = om.MMatrix(cmds.xform(dag_node, query=True, worldSpace=True, matrix=True))
    matrix_inv = matrix.inverse()
    bmin *= matrix_inv
    bmax *= matrix_inv
    bmin = om.MVector(bmin)
    bmax = om.MVector(bmax)
    center = (bmin + bmax) / 2.0
    
    return list(center)
    
    
center = get_local_center(transform)
cmds.setAttr(transform + ".selectHandle", center[0], center[1], center[2], type="float3")
```

**OR**
- Always set the Selection Handle to origin [0, 0, 0] - which would only be needed on first load.

```python
from maya import cmds

cmds.setAttr(transform + ".selectHandle", 0, 0, 0, type="float3")
```

Likely updating the center is the best workflow so that it'd still work fine for loaded geometry that is not even near the origin. This could be the case for loaded 'pointcaches' from animation for example.

**Preview of current issue**

I loaded version 1 and 2 of a simple geometry that changed in height, then also updated the older loaded version 1 to 2. Note the difference in selection handle compared to the geometry.

![update_model_display_handle_issue](https://user-images.githubusercontent.com/2439881/147364359-518913a6-7061-44b2-8eb6-bf8e12ac0f4e.gif)

The issue is more prominent with published pointcaches of e.g. character animation that was moved to a different location in newer versions than when it was initially loaded.

---

**Animation/Time-related issues**

This issue could be even more complicated with animated geometry too since the selection handle would currently be different based on the frame the user is on when the animation was loaded. So if a character moves from left to right in a shot then when loading the character with the timeline near the beginning would have the handle on the left side, and otherwise more to the right.

[cuID:[OP-2252](https://app.clickup.com/t/1yk18nt)]

**Comment by BigRoy** [comment]
Regarding the time related centering it doesn't seem trivial to get the good bounding box at another frame without actually changing the current time. So it could get slow for larger scenes.

Here's a quick test.
```python
import maya.api.OpenMaya as om
from maya import cmds
    
def get_local_center(dag_node, time=None):
    
    original_time = cmds.currentTime(query=True)
    if time is not None:
        cmds.currentTime(time, update=True)
    
    # The bounding box of a transform is always returned in world
    # space even with the `objectSpace` flag - that only works on meshes
    # directly. So we just make the bounds local space ourselves.
    bounds = cmds.xform(dag_node, query=True, worldSpace=True, boundingBox=True)
    
    bmin = om.MPoint(bounds[:3])
    bmax = om.MPoint(bounds[3:])
    matrix = om.MMatrix(cmds.xform(dag_node, query=True, worldSpace=True, matrix=True))
    matrix_inv = matrix.inverse()
    bmin *= matrix_inv
    bmax *= matrix_inv
    bmin = om.MVector(bmin)
    bmax = om.MVector(bmax)
    center = (bmin + bmax) / 2.0
    
    cmds.currentTime(original_time, update=True)
    
    return list(center)
```

Example usage:
```python
transform = cmds.ls(sl=1)[0]
center = get_local_center(transform, time=1000)
cmds.setAttr(transform + ".selectHandle", center[0], center[1], center[2], type="float3")
```

**Comment by BigRoy** [comment]
Leaving this here for future reference. This is a hacky way to retrieve the bounding box on another frame without requiring to actually change the current time that seemed to work in some initial tests:
```python
import maya.api.OpenMaya as om
from maya import cmds
import contextlib


def get_plug(attr, context=None):
    sel = om.MSelectionList()
    sel.add(attr)
    return sel.getPlug(0)


@contextlib.contextmanager
def dg_context(context):
    original = context.makeCurrent()
    try:
        yield
    finally:
        original.makeCurrent()
    
    
def get_local_center(dag_node, time=None):
    
    mtime = om.MTime(time, unit=om.MTime.uiUnit())
    context = om.MDGContext(mtime)

    with dg_context(context):
        # The first call to cmds.xform within the MDGContext returns the wrong
        # value so we call it once first just so consecutive call returns
        # the correct value
        cmds.xform(dag_node, query=True, worldSpace=True, boundingBox=True)
        
        bounds = cmds.xform(dag_node, query=True, worldSpace=True, boundingBox=True)
        
    bmin = om.MPoint(bounds[:3])
    bmax = om.MPoint(bounds[3:])
    matrix = om.MMatrix(cmds.xform(dag_node, query=True, worldSpace=True, matrix=True))
    matrix_inv = matrix.inverse()
    bmin *= matrix_inv
    bmax *= matrix_inv
    bmin = om.MVector(bmin)
    bmax = om.MVector(bmax)
    center = (bmin + bmax) / 2.0
    
    return list(center)
    
transform = cmds.ls(sl=1)[0]
t = 1000
center = get_local_center(transform, time=t)
cmds.setAttr(transform + ".selectHandle", center[0], center[1], center[2], type="float3")
```

**Comment by mkolar** [comment]
This is exactly one of those issues, that is most certainly a bug, but I'm not sure if it's worth the time we'd spend trying to make it work, just for  selection handle :D nevertheless I'm leaving it here for now, if someone is bored on friday evening :)

**Comment by BigRoy** [comment]
We personally ended up actually disabling the Selection Handles since the majority of artists didn't prefer them - those who did use them actually had their own little tools to quickly enable/disable Selection Handles on nodes anyway. So no priority on our end.

**Comment by BigRoy** [comment]
Closing this since it's not an issue since then for us anymore.
