### ISSUE TITLE
Maya: Update camera resets viewports currently looking through that camera

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#2461]
### Issue

Loading a camera and updating it resets any modelPanel to a different camera (because as the reference gets updated it temporarily isn't there and maya ends up resetting it).

**To reproduce:**

1. Load a camera
2. Set a viewport to look through the camera
3. Go to OpenPype > Manage.. and update the loaded camera to a new version
4. The viewport now currently isn't looking through the camera anymore.

**Expected behavior**

Less interuption for the user with their current scene would be nice - so basically no change to the viewports and their cameras except for the camera being updated.

**Additional context**

I have an existing fix for this outside of OpenPype here: https://github.com/Colorbleed/colorbleed-config/commit/2d1f60082c4360c6b4d011bbe49cf3c9a0f9855a

I'd just like to know whether anyone else also feels this is a nice enough user experience improvement to implement it.

[cuID:[OP-2261](https://app.clickup.com/t/1yyjjga)]

**Comment by tokejepsen** [comment]
Would say go for it since you already have a fix for it.
