### ISSUE TITLE
New publisher - repair action logging

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#2468]
**Describe the bug**
If a repair action is logging anything it is not shown anywhere in develop log

**To Reproduce**
jsut add log.info(...) into your repair action and hit Repair button on failed validator

**Expected behavior**
any repair action log should appear under related context - instance plugin should add the log under instance log.

[cuID:OP-2270]

**Comment by iLLiCiTiT** [comment]
Joined with https://github.com/ynput/OpenPype/issues/4036
