### ISSUE TITLE
fps rounding issue in validate_maya_units.py

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/OpenPype#2620]
we did some math magic to round fps correctly because of the specific way ftrack was storing fps

this was changed apparently and now our rounding is causing troubles in Maya

```
 # openpype.hosts.maya.api.lib : Setting scene FPS to: '29.97fps'
.
// pyblish.ValidateMayaUnits : Units (time): 29.98 FPS // 
.
AssertionError: Scene must be 29.97 FPS(now is 29.98) //
```

ordinary python rounding should fix the problem
`fps = round(context.data['fps'], 2)`

[cuID:OP-2549]

**Comment by antirotor** [comment]
Closed by #4424
