### ISSUE TITLE
Quick way to produce reviews from ACEScg Maya renders

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#2712]
## Problem

Currently we don't handle colorspace information on review level - default ffmpeg profile is set to apply gamma 2.2 and thats it. It works for classic linear workflow, but not for anything else.

We now have requests to create reviews from ACEScg renders. Until #2579 (and discussion #2574) is properly resolved, we need quicker fix. Quick overview what can be done:

- mark project as using ACEScg for renders (collector should pick it up from Maya settings)
- using custom family name (as we currently have no easy mechism to do it differently) mark render instance as ACEScg
- in plugins generation reviews and thumbails, first feed exrs to OIIO and apply color transform and pipe it from OIIO to ffmpeg to encode it

### Questions

- how could that be re-used (with changes ofc) in implementing #2579
- how would it cope with super big exrs memory-wise

[cuID:25r576d]

**Comment by tokejepsen** [comment]
> mark project as using ACEScg for renders (collector should pick it up from Maya settings)

For a quick fix I recommend that we discard marking the project as using ACEScg cause that a bigger bit of development as it involves hierarchical data which needs more UI. Maya would inherit this data in the preflight phase and setup the workfile. Without marking the project and getting workfile setup, the client can still manually setup the workfiles.

> using custom family name (as we currently have no easy mechism to do it differently) mark render instance as ACEScg

From the sounds of #4291, we would not need to give the render instances any specific family. We can just collect the colorspace from Maya and inject that into the instance `colorspaceData`.

Unless we need something quicker and cant wait for #4195 ?

**Comment by jakubjezek001** [comment]
> From the sounds of https://github.com/ynput/OpenPype/pull/4291, we would not need to give the render instances any specific family. We can just collect the colorspace from Maya and inject that into the instance colorspaceData.

I presume there is no harm to base branch on the #4195 already and integrate provided functionality in `openpype\pipeline\publish\publish_plugins.py:ExtractorColormanaged`.
