### ISSUE TITLE
Houdini: Farm publishing/rendering

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#2722]
## Feature

Publishing to/on farm - Deadline and RoyalRender

🛠️ **Description work in progress**

[cuID:[OP-2637](https://app.clickup.com/t/25xn6hn)]

**Comment by BigRoy** [comment]
We have rendered on the farm with Deadline in both Redshift and Arnold before. Let me know what you need specifically from our end and I might be able to contribute. 👍

**Comment by antirotor** [comment]
Well exactly this - rendering and publishing of redshift renders, along with arnold and matra. Karma probably to if we solve usd resolver. And we'll need to do it for Deadline and RoyalRender, so something nice, abstract and extendable 💎
