### ISSUE TITLE
Houdini: Look dev

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#2723]
## Feature

Add Look dev support to Houdini. Based on HDAs or USD

🛠️ **Description work in progress**

[cuID:[OP-2638](https://app.clickup.com/t/25xn813)]

**Comment by BigRoy** [comment]
This PR https://github.com/ynput/OpenPype/pull/5925 should be a kickstart for Houdini Solaris lookdev with USD.

Would be good if maybe in the context of that the _Description work in progress_ could be expanded to lay out any requirements for the feature.

**Comment by BigRoy** [comment]
This is implemented in AYON via USD with https://github.com/ynput/ayon-core/pull/295
Outside of USD the best workflow likely is making dedicated HDAs for character's looks.
