### ISSUE TITLE
Creating an custom naming template breaks app launch

### ISSUE THREAD

**Issue by gabormarinov** [ynput/OpenPype#2762]
**Describe the bug**
Creating an entry in `project_anatomy/templates/others` causes app launch to fail with the message: ˛`Error in anatomy.format: "Anatomy templates can't be filled. Anatomy key Path has invalid inner key folder.`

**To Reproduce**
1. Go to 'project_anatomy/templates/others`'
2. Create  a new naming template

![image](https://user-images.githubusercontent.com/8620515/154680912-3b936157-241c-403d-b81f-c72973b2be40.png)

3. Save
4. Try to launch an app (eg. Maya)
5. Error

![image](https://user-images.githubusercontent.com/8620515/154680831-d0d35e28-eff7-4bd5-ac95-539f76cf7dbc.png)

[cuID:26966k7]

**Comment by antirotor** [comment]
I can confirm the bug.

**Comment by iLLiCiTiT** [comment]
To solve the issue now replace keys:
- `Folder` -> `folder`
- `File` -> `file`
- `Path` -> `path`

Question is: do we want to allow fill other than these keys in `other` section? If not then we can define strict dictionary schema for these keys.

**Comment by antirotor** [comment]
this might be confusing because keys in built-in templates start with capitalized letter like this:
![image](https://user-images.githubusercontent.com/33513211/155190808-dcb452dd-c095-415a-aad4-179331092656.png)

so it is obvious that users will try to replicate it.

**Comment by gabormarinov** [comment]
> this might be confusing because keys in built-in templates start with capitalized letter like this: ![image](https://user-images.githubusercontent.com/33513211/155190808-dcb452dd-c095-415a-aad4-179331092656.png)
> 
> so it is obvious that users will try to replicate it.

This is exactly what I did: I replicated the keys as it seemed like the correct way. As a user I would expect an one line explanation about that I have to use lower case letters only, besides the validator.

**Comment by antirotor** [comment]
This is still present in v3 but solved by AYON
