### ISSUE TITLE
Skip opening of last workfile doesn't work for Houdini

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#2788]
## Bug

Currently there's no way to skip opening of last workfile for Houdini. This is probably not connected to PR that enabled this feature for Houdini (#2767).

**Comment by BigRoy** [comment]
> This is probably not connected to PR that enabled this feature for Houdini (https://github.com/pypeclub/OpenPype/pull/2767).

This likely means this problem also exists for other applications since it uses the same logic. Could you confirm this issue also occurs with Maya or another host?

**Comment by antirotor** [comment]
Actually it does work only if one version of DCC is specified in the Settings. If there are more, it stops working.

**Comment by BigRoy** [comment]
I have a feeling that #3822 actually resolved this issue. Correct @kalisp @antirotor @iLLiCiTiT ? :) Should we close this?

**Comment by iLLiCiTiT** [comment]
Resolved by https://github.com/ynput/OpenPype/pull/3822
