### ISSUE TITLE
Houdini bgeo publishing

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#3098]
## Feature

Add bgeo publishing/loading to Houdini. Support for `bgeo` and `bgeo.sc`.

[cuID:OP-3129]

**Comment by BigRoy** [comment]
Has work on this started yet? If not, I'd be happy to set up the barebones functionality for this.

**Comment by antirotor** [comment]
Nope, nothing is done yet.

**Comment by antirotor** [comment]
FYI I've just added for one client very simple loader of bgeo to houdini. Nothing fancy. Publishing from standalone publisher has one limitation - it doesn't support `bgeo.sc` adn `bgeo.gz` but only `bgeosc` and `bgeogz` due to the limitations we have of handling file extentions.

**Comment by BigRoy** [comment]
Due to other priorities and production needs on our end lately I don't feel me as assignee is the best candidate for this on short-term - sorry about that.
