### ISSUE TITLE
Loader: Show which subsets are already loaded in the scene

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#3124]
**Is your feature request related to a problem? Please describe.**

Artists requested being able to highlight or see which subsets in the Loader are already loaded into the current scene.

**Describe the solution you'd like**

Likely an extra column that might show whether it's loaded with a potential number of loaded entries as value so that the user could sort by that column would already allow the user to be able to find unloaded content without too much effort.

It would be nice to make it a custom delegate that could also show e.g. an orange warning icon when the loaded content is actually loading an older version than the latest version and maybe a green check mark if it's currently using the latest loaded version.

Bonus points if hovering over it would show a tooltip or alike that could detail similar information as the Scene Inventory would show about the loaded content, like the container names, used loaders, etc. to find out whether e.g. the Alembic or another representation was loaded.

Having this visual in the Loader allows to also easily detect any entries that might have gotten a new publish under a new subset name or alike, e.g. an FX derivative of a (part of a) character.

**Describe alternatives you've considered**

Artists would currently open the Scene Inventory / Manager next to it to check against currently loaded content but visually it's not a 1-to-1 correspondence to the Loader list of subsets so it's relatively time consuming to compare against it - plus large scenes with many loaded assets get extra difficult in this way. Being able to easily find or filter already content in the Loader would solve that.

[cuID:OP-3167]

**Comment by mkolar** [comment]
That's a very good idea actually. It does muddle the waters a bit between loader and inventory, but it woudl certainly be useful

**Comment by BigRoy** [comment]
This has been implemented with #3649 but doesn't tell you anything about whether it's latest version or not, but I believe it's proven useful as it is.

I'll close this issue until anyone has additional requests for the feature.
