### ISSUE TITLE
Tools: Propagating project tool settings into existing assets 

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#3150]
**Is your feature request related to a problem? Please describe.**

When adding a new Tool default to a project existing assets are left unaltered. With many assets it can be intensive to propagate a new tool or updated tool into the project because of this.

There are two problems:
- It's unclear that adding a Tool to the project doesn't directly influence existing assets
- It would be nice if the Project Manager or settings would have functionality to easily "propagate an update"

**Additional context**

- [Tools don't work for existing assets came up on Discord](https://discord.com/channels/517362899170230292/563751989075378201/969262587575418931)

[cuID:[OP-3194](https://app.clickup.com/t/29qzy90)]

**Comment by mkolar** [comment]
We've now shifted the focus onto the web based project manager for v4 release, where we're counting on this functionality, so in the current PM, we probably won't be adding this.

**Comment by BigRoy** [comment]
AYON inherits by hierarchy automatically unless overrides are set, so this is solved there.
