### ISSUE TITLE
Project Manager: Saving while another user added a task removes the task

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#3187]
**Describe the bug**

We hit an issue where one User added a Task to an Asset that hadn't shown in the Project Manager for another User yet. The other user also added a (different) Task on the same Asset.

Saving by the second user removed the Task added by the first User. 

I believe this "problem" has a bigger chance of occurring due to the Project Manager remaining open in the background in Tray when closing it and reopening it. As such, it might remain in its unrefreshed old state from before closing since it doesn't seem to refresh on showing it again?

**To Reproduce**
1. Have two Users open the Project Manager
2. Add a "Modeling" Task to Asset, then Save.
3. Other User add a "Rigging" Task to Asset, then Save.
4. Browse in Launcher to the Asset. Only "Rigging" task will be available.

**Expected behavior**

It should persist as much as possible on conflicting Users updating the project in the database. The absolute worst case scenario should be a pop-up on Save saying something like a "Conflict on Save" describing which assets/changes are in conflict and should disallow the save without a refresh and have the User refresh with its own changes overlaid on top of it.

[cuID:[OP-3254](https://app.clickup.com/t/2au9v41)]

**Comment by mkolar** [comment]
This is indeed quite a problem. however with the amount of usage we see for the project manager (practically zero) and the sjiny new web based project editor that is being developed for v4, I'm not sure it's worth putting much effort into this. PM right now is a very simple tool, never really intended to be used by multiple people in the studio.

**Comment by BigRoy** [comment]
Irrelevant in AYON
