### ISSUE TITLE
Project Manager: Can't copy paste Tasks into multiple selected Assets at once

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#3188]
**Describe the bug**

In the Project Manager you can copy/paste Tasks from one Asset to another. However it doesn't work when trying to paste Tasks into multiple selected assets, it will only copy into the active selected Asset and not all of them.

**To Reproduce**
1. Click some Tasks on an existing Asset.
2. Press CTRL+C to Copy into memory
3. Select Multiple Assets
4. Press CTRL+V to paste the tasks

**Expected behavior**

The copied Tasks should be pasted into all selected assets.

[cuID:OP-3255]

**Comment by mkolar** [comment]
This has already been implemented
