### ISSUE TITLE
Split remote publishing targets into 2

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/OpenPype#3287]
## Description
Current target `remote` is used in 2 different ways.

1. Real remote publish
Is used in Maya remote publishing ([PR](https://github.com/pypeclub/OpenPype/pull/3225)). Artist works in scene, create instances to publish, but during publishing is workfile sent to farm where the full publish happens (DCC is opened, host is intalled, workfile opened and publishing starts).

2. Magic remote publish
Is used in webpublisher where is known only workfile but the workfiles does not contain created instances. Instances are faked during collection phase of publishing using logic defined by the collector -> instances magicaly appear even if were not created by artist. Otherwise works the same way (DCC is opened, host is installed, workfile opened and publishing starts).

The only difference is in collection phase where 1st approach looks into scene for instances and 2nd approach create them on the fly. At We would also like to avoid calling the 2nd approach `webpulisher` target because the same approach could be in theory used from standalone publisher or even directly from host in some cases. From my point of view `remote` target is enough explicit for 1st usage and 2nd should be renamed, but any better suggestions are welcomed.

## Note
If your suggestion is `farm` then that's already used for publishing of files based on passed data out of DCC (Some output was created on farm which is just validated and integrated in separated process).

## Suggestions
- `auto-remote`
- `automated`

[cuID:[OP-3360](https://app.clickup.com/t/2eqzt8e)]

**Comment by mkolar** [comment]
I think `automated` target is pretty good in this case, considering it's the only time we're really automating the full process.
