### ISSUE TITLE
default uvset name for alembic output

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/OpenPype#3311]
When Maya is used for lighting on a project where alembic data is produced by other DCCs, there is a constant issue with the default uv set name. Maya expects to have at least one uv set name "map1"
In case there is no such uv set name, it will create an empty map1 uv set effectively destroying texture shading on such model.

To prevent this from happening we should have (an optional) validator for the uv set name to be map1 in all DCCs

![image](https://user-images.githubusercontent.com/352795/173031709-370cb7c6-47ad-43f3-9308-11c65172a0e6.png)

[cuID:[OP-3372](https://app.clickup.com/t/2f3ht3k)]

**Comment by BigRoy** [comment]
There is [one for Maya](https://github.com/pypeclub/OpenPype/blob/8432e94615a75216e7172cf46f1370fff806bf13/openpype/hosts/maya/plugins/publish/validate_mesh_uv_set_map1.py#L8) - but in settings it's [disabled by default](https://github.com/pypeclub/OpenPype/blob/c31dbf45d50986179a5b145288433ed2b0a7a4de/openpype/settings/defaults/project_settings/maya.json#L321-L325).

Are you specifically requesting it for another DCC? If so, which ones are you trying to tackle currently?

**Comment by BigRoy** [comment]
Within AYON this may be best moved to the individual addons for which it is relevant - e.g. `ayon-blender` or cinema4D if it ever gets an implementation?
