### ISSUE TITLE
Maya: Create Render sets resolution and breaks pixel aspect ratio

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#3402]
**Describe the bug**

When doing OpenPype > Create... > Render then OpenPype resets the render settings for the current renderer.

If the current render resolution in render resolution mismatches the one in the project manager / database the resolution is reset in render settings but this breaks the Pixel Aspect ratio.

**To Reproduce**
1. Open an asset that has resolution set to 1920x1080 and pixel aspect to 1.0 (in project manager)
2. In Maya workfile set your render resolution to 50x50
3. OpenPype > Create... > Render
4. Now your render settings pixel aspect ratio is incorrectly set to 0.563

**Expected behavior**

1. Create Render should set the settings correctly.
2. And I'd prefer a studio wide setting to disable Create Render to actually mess with render settings in the scene altogether.

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/2439881/175311617-9f49df06-66e6-4a9c-860e-ba0337884036.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Host: Maya 2022
 - Renderer: Redshift, Arnold, V-Ray (reproducable with all of these)

[cuID:[OP-3453](https://app.clickup.com/t/2hz0tna)]

**Comment by antirotor** [comment]
This needs to be fixed. And

>And I'd prefer a studio wide setting to disable Create Render to actually mess with render settings in the scene altogether.

shoud be addressed here https://github.com/pypeclub/OpenPype/pull/3097/files#r906234521

**Comment by BigRoy** [comment]
Haven't seen this in AYON - will close it for now.
