### ISSUE TITLE
Enhanced system of priorities

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#3613]
## Feature

Artist can set priority on the render instance. That's his choice as he understands his context. Leads/Supervisors may have bigger picture over the assets and shots so they can set priorities on them too. Some task types can have higher priority then the others. Final priority set on the job in Deadline/RoyalRender should be calculated by weighting of all these priorities and these weights should be set in the Settings.

### Example:

Artist Bob set priority 70 on render instane in Maya, He is working on the shot S010. Alice is working on car asset and she's doing lookdev. She also sets her priority to 70 on render instance in Maya used for review. There is also modeler Fred that wants to render out turntable of his model, and of course he set priority 70 to his render instance. Their Lead knows, that rendering of the shot has higher priority so he sets on that particular shot priority 80. Default priority on all assets is 50.

Without the weighting, all jobs would land on farm with the same priority and it might happen that the more important render of the shot will be the last. But with weights, priority set on the shot by Lead will shift shot render priority much higher and also if there is a weight set on task priority, it will correctly sort order so first will be the shot render, then lookdev and then the turntable.

[cuID:[OP-3705](https://app.clickup.com/t/2p2mq1b)]

**Comment by mkolar** [comment]
This got no interest since it was created from the community of clients. let's close it and revisit if it reappears.
