### ISSUE TITLE
Settings: Copy overrides to different project or studio default

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/OpenPype#3668]
## Description
In some cases it is handy to be able use project overrides as studio defaults, because the project just work perfectly. Or in some cases it could be also handy to "copy" overrides to different project.

### Unclear issues
If project overrides should be passed to a different project.
- Should just replace the values for the destination project? Or should "update" it, meaning that settings groups which are not in source overrides are kept untouched,

If project overrides should be passed to studio defaults it should probably "not" remove other studio defaults. In that case "update" the values is requirement otherwise even the source project would stop working without "original" studio defaults.

[cuID:[OP-3728](https://app.clickup.com/t/2q50nvu)]

**Comment by m-u-r-p-h-y** [comment]
another similar #3818
