### ISSUE TITLE
Maya: Extractor "Look" fails on maketx utility for image texture conversion (Png>tx) /  or missing OCIO.config problem?!

### ISSUE THREAD

**Issue by LiborBatek** [ynput/OpenPype#3814]
Unable to publish asset look because of crash during image texture conversion from PNG to tx format using maketx utility.

![image](https://user-images.githubusercontent.com/112623825/189135668-10086043-5a42-45a8-b11b-36a20533faa6.png)

```
Instance: 
lookMain
Message: 
Command 'D:\REPO\OpenPype\vendor\bin\oiio\windows\maketx.exe -v -u --unpremult --checknan --oiio --filter lanczos3 D:\PROJECTS\OP01_CG_demo\assets\props\airConditionerB\work\lookdev\textures\ac_DefaultMaterial_Roughness.1001.png --sattrib sourceHash ac_DefaultMaterial_Roughness,1001,png|1652796456,0|325183|maketx  --colorconfig D:\REPO\OpenPype\vendor\bin\ocioconfig\OpenColorIOConfigs\nuke-default\config.ocio -o C:\Users\Libor\AppData\Local\Temp\pyblish_tmp_w4v7_ip1\resources\ac_DefaultMaterial_Roughness.1001.tx' returned non-zero exit status 1.
Line: 
512
Traceback: 
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\extract_look.py", line 252, in process
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\extract_look.py", line 389, in process_resources
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\extract_look.py", line 549, in _process_texture
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\extract_look.py", line 121, in maketx
  File "C:\Program Files\Autodesk\Maya2022\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Program Files\Autodesk\Maya2022\Python37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'D:\REPO\OpenPype\vendor\bin\oiio\windows\maketx.exe -v -u --unpremult --checknan --oiio --filter lanczos3 D:\PROJECTS\OP01_CG_demo\assets\props\airConditionerB\work\lookdev\textures\ac_DefaultMaterial_Roughness.1001.png --sattrib sourceHash ac_DefaultMaterial_Roughness,1001,png|1652796456,0|325183|maketx  --colorconfig D:\REPO\OpenPype\vendor\bin\ocioconfig\OpenColorIOConfigs\nuke-default\config.ocio -o C:\Users\Libor\AppData\Local\Temp\pyblish_tmp_w4v7_ip1\resources\ac_DefaultMaterial_Roughness.1001.tx' returned non-zero exit status 1.

```

[cuID:OP-3944]

**Comment by LiborBatek** [comment]
also attaching image file which caused it...
![ac_DefaultMaterial_Roughness 1001](https://user-images.githubusercontent.com/112623825/189136128-38b0603b-2254-4424-9f9e-1832ba161226.png)

**Comment by BigRoy** [comment]
@LiborBatek This would be better to debug if the subprocess output would be logged as well.

Could you [change this logic](https://github.com/pypeclub/OpenPype/blob/4334adda1a9af29a62ef04725a8059b3b030e329/openpype/hosts/maya/plugins/publish/extract_look.py#L122-L129) to something like this:
```python
    except subprocess.CalledProcessError as exc:
        # Log subprocess output
        self.log.error(exc.output)
        
        # Log exception
        self.log.error(traceback.format_exc())
        raise

    return out
```

And then try again?

The `subprocess.CalledProcessError.output` should be the console output produced by the subprocess in the case of an exception. Likely `maketx` will have logged more useful information there and can help us pinpoint the issue.

**Comment by LiborBatek** [comment]
@BigRoy  thx I invited guys to look on that ...I m just not able to do it myself being just poor cg artist :)

**Comment by antirotor** [comment]
This is caused by "missing OCIO config" error in `maketx`. Strange as it happens only to specific files in specific scenarios (and with OCIO config present). I'll add more details.

**Comment by BigRoy** [comment]
Could it be that the subprocess paths passed along don't get the backslashes or spaces in paths escaped correctly? So that only some OCIO paths might be invalid? We could try enforcing forward slashes?

@LiborBatek @antirotor Would [this branch work](https://github.com/BigRoy/OpenPype/tree/extract_look_maketx)? 

[Here's a diff](https://github.com/pypeclub/OpenPype/compare/develop...BigRoy:OpenPype:extract_look_maketx?expand=1) without opening a PR directly.

**Comment by BigRoy** [comment]
Also that vendorized OCIO config being present would only be there if one would have correctly pulled the latest binaries and rebuild environment, etc. along with the recent refactoring instead of only checking out this branch. That could've also been the problem?

**Comment by antirotor** [comment]
@LiborBatek is this still happening?

**Comment by LiborBatek** [comment]
@antirotor did test it in latest develop and works normally without any glitch!

![image](https://user-images.githubusercontent.com/112623825/212097642-4806a69b-9040-44a4-9dbb-830a4432fbd8.png)

**Comment by antirotor** [comment]
> @antirotor did test it in latest develop and works normally without any glit
