### ISSUE TITLE
Nuke: open_file function wouldn't open .autosave file

### ISSUE THREAD

**Issue by jeangjenq** [ynput/OpenPype#3881]
**Running version**
3.14.0

**Describe the bug**
Using OpenPype's open_file function doesn't load nuke's autosave files. Workfiles > Open in a running nuke instance wouldn't have "load autosave" prompt at all, while launching nuke on a task will have nuke's default "load autosave" prompt, but won't actually open autosave.

**To Reproduce**
1. Launch Nuke on a task with OpenPype. 
2. Click yes on Nuke's default load autosave prompt.
3. Nuke will open the .nk file instead of loading in the .nk.autosave file

**Expected behavior**
Nuke loads the autosave file after hitting "Yes" on "load autosave" dialog.

**Desktop (please complete the following information):**
 - OS: Windows
 - Host: NukeX 13.1v2

**Additional context**
Believe this is caused by [workio.py](openpype/hosts/nuke/api/workio.py)
Changing line 30 to the following address the issue by introducing a second "load autosave" prompt.
```
nuke.scriptClear()
autosave = "{}.autosave".format(filepath)
autosave_prompt = "Autosave detected.\nWould you like to load the autosave file?"
if os.path.isfile(autosave) and nuke.ask(autosave_prompt):
    nuke.scriptReadFile(autosave)
else:
    nuke.scriptReadFile(filepath)```


[cuID:OP-4096]

**Comment by jeangjenq** [comment]
```
nuke.scriptClear()
autosave = "{}.autosave".format(filepath)
autosave_prompt = "Autosave detected.\nWould you like to load the autosave file?"
if os.path.isfile(autosave) and nuke.ask(autosave_prompt):
    nuke.scriptReadFile(autosave)
else:
    nuke.scriptReadFile(filepath)```

The workaround I posted doesn't account for user changed their autosave location in nuke preference.
I tried changing the line about autosave location to 
`autosave = nuke.tcl("return " + nuke.toNode('preference')['AutoSaveName'].value())`
However, nuke doesn't seem to know where that is when the script hasn't fully opened.

Forcing all users to use default autosave location for now.

**Comment by jakubjezek001** [comment]
already fixed by:
https://github.com/ynput/OpenPype/pull/5107
https://github.com/ynput/OpenPype/pull/5295
