### ISSUE TITLE
Houdini: Switching context doesn't update variables

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#4035]
## Bug

When switching context in Houdini, sometimes `$HIP`/`$JOB` are not updated.

[cuID:[OP-4326](https://app.clickup.com/t/30u2296)]

**Comment by BigRoy** [comment]
Could you elaborate on this issue?

- `$HIP` is always the workfile path and as such, how should this update?
- `$JOB` is a custom attribute definition which as far as I know OpenPype doesn't set it explicitly by default at all. In Houdini it's somewhat the equivalent to what setting workspace would be in Maya, [as be seen here for how it's used to "Set project"](https://www.sidefx.com/docs/houdini/basics/project.html). 
    - However, do note that `$JOB` defaults to the _current working directory_ that Houdini launched with which [this Houdini pre-launch hook](https://github.com/ynput/OpenPype/blob/b95e79e0d0374a3b95be5e5f21712975470dca93/openpype/hosts/houdini/hooks/set_paths.py#L17) ends up setting. Should we maybe make that more explicit by instead setting the `JOB` env var?

It's also good to note what [the docs mention about `$JOB`](https://www.sidefx.com/docs/houdini/basics/project.html#tips-and-notes):

> The value of $JOB is saved with the scene (.hip) file. So once you associate a given scene file with a project using File ▸ Set Project and save it, you don’t have to use File ▸ Set Project again the next time you open the scene file.

---

@antirotor So is this issue about updating JOB on Task change?

**Comment by MustafaJafar** [comment]
I think this PR is related
https://github.com/ynput/OpenPype/pull/5532

**Comment by MustafaJafar** [comment]
@BigRoy 
Hey, let's revisit this issue 

## Some Facts
### HIP
I saved Houdini file to desktop and published my job and Houdini addon oddly doesn't complain ?! 

![image](https://github.com/ynput/OpenPype/assets/20871534/a1aca95e-6ea6-42d1-a58b-ab9fca310749)


### JOB
as we discussed before, Houdini addon doesn't manage `$JOB` at all.
So, it's managed  according to Houdini's default which is as far as I know : 
1. set `$JOB` to `$HIP` 
2. users are allowed to set `$JOB` manually 
3. developers cam set `$JOB` programmatically by using `hou.hscript("set JOB=" + job)` 

----------
## Quick tests: 
### Launch Task in Houdini for the first time 
Houdini addon succeed in open Houdini file in the correct directory but doesn't save the first file, so artist must  use the workfile tool to save it. 

Also, `$HIP` and `$JOB` both are set to working directory and no `$HIPNAME` yet. 
![image](https://github.com/ynput/OpenPype/assets/20871534/04481546-18dd-41cf-baca-d59d05180f7d)
 
### Launch Task in Houdini
, `$HIP` and `$JOB` both are set to working directory and `$HIPNAME` showing the current file name
![image](https://github.com/ynput/OpenPype/assets/20871534/424d9408-d045-43a7-9c04-70070dd0fbc2)

### Switch context
From the opened Houdini session there are two possibilities

#### open another workfile 
Python env vars may not be updated but hscript vars are there! and if I close and reopen the same file, I will find python vars values are the same as the hscript ones. 

> I think there should be a post open callback to sync hscript vars and their python os.environ twins 

![image](https://github.com/ynput/OpenPype/assets/20871534/633f99bb-2667-49bb-83d5-da955f10dcb1)

#### Save current workfile to another asset

The new workfile will hold the value of the old workfile

![image](https://github.com/ynput/OpenPype/assets/20871534/28b86264-a110-4631-9f08-393ac2ead2f9)

---
So, How should we manage HIP and JOB at these cases ?

**Comment by BigRoy** [comment]
Regarding the env vars instead of the hscript vars - I didn't even know they were also env vars and I'm not sure if there's a reason I should care about their values if there's no required use for them?

---

> I saved Houdini file to desktop and published my job and Houdini addon oddly doesn't complain ?!

Correct, no hosts do this as far as I know. It _can_ be non-trivial to enforce saving in a certain location unless you **force** it to be within the workdir. This could easily be a global validation plugin if needed.

> **Save current workfile to another asset**
> The new workfile will hold the value of the old workfile

Looking at your screenshot - this seems to only be the case for `$JOB`. 

----

FYI, We've managed JOB outside of OpenPype and thus it is NEVER set to the initial HIP anyways. Then looking at your examples all works as expected HIP and HIPNAME update as expected, JOB is our custom var.

If you're looking to sync JOB to HIP then I'd say you should instead just be using HIP. If you have a custom need for JOB at your studio - then set it to whatever your studio needs. I still don't see a reason for OpenPype itself to force something into JOB.

**Comment by krishna8008** [comment]
IMO, This is more of template(folder structure related): 
$JOB should indicate the task path,
Hipfiles should be saved inside a "hip" folder, so it won't look clumpsy when we open task in file explorer. its more convienient for artists to save there files either $JOB(task path) or $HIP(hipfile path(folder inside $JOB))

Also it helps when we want to share files with outsource people who are not using OP*

**Comment by MustafaJafar** [comment]
@BigRoy  Thank for helping me think differently.. 
The idea is not to force a certain value but to manage that value if it exists and adding an option for admins to specify the desired value and I believe there's a little space for improvement here.

---
Let's jump to the issue 
To fix the env vars when switching context, we need to agree/specify the values of these env vars. 

This how I imagine it : 

### Regarding `$HIP` 
I think that we
- don't need to set `$HIP` (the working directory) as it's managed by Houdini and [this Houdini pre-launch hook](https://github.com/ynput/OpenPype/blob/b95e79e0d0374a3b95be5e5f21712975470dca93/openpype/hosts/houdini/hooks/set_paths.py#L17)
- might add a validator to check if the `$HIP` points to a location that makes sense (e.g. not desktop in my opinion)

### Regarding `$JOB` 
It should be up to studios. however, some hints ; it can be 
- Arbitrary path 
- Project path 
- asset category path (e.g. `characters`, `props`)
- asset path
- task path (which may not be the working directory as you pointed out [here](https://github.com/ynput/OpenPype/pull/4830#discussion_r1164225591) )
- nothing at all 

And the specified value is what should be managed when switching contexts (as the path may be asset specific)
I think it would be nice to have a dedicated option for that in settings + some validator or call back that make sure that this value is maintained (as artists can ~choose the dumb way and~ set project manually 🙂)

**Comment by BigRoy** [comment]
The **job** setting that updates per context based on Project Settings sounds fine with me if studios can enter their own template for it in settings. It could even have a checkbox whether the callback runs on Context change or not.
