### ISSUE TITLE
Publisher: add more abstract methods

### ISSUE THREAD

**Issue by kalisp** [ynput/OpenPype#4054]
**Is your feature request related to a problem? Please describe.**
`Publisher` expects more methods which are not abstract currently in any base class or interface and therefore it is a bit difficult to know that they need to be implemented.

**Describe the solution you'd like**
At least these methods should be added:
- install
- ~uninstall~
- get_context_data
- update_context_data

And maybe:
- ~list_instances~ `see comment lower`
- ~remove_instance~

These were expected for SubsetManager (for host where is not totally clear which publishable instances are there). SubsetManager is probably obsolete and replaced with Publisher.

[cuID:OP-4339]

**Comment by iLLiCiTiT** [comment]
Few notes:
- `install` should not be abstract but should be available with docstring
- `uninstall` is pointless method that was never used in openpype
- `get_context_data` and `update_context_data` is abstract in `IPublishHost`
- `list_instances` and `remove_instance` is only for SubsetManager which will be removed with new publisher

**Comment by BigRoy** [comment]
> uninstall is pointless method that was never used in openpype

I've actually started using `uninstall()` in [Substance Painter integration](https://github.com/ynput/OpenPype/pull/4283) since it's installed through an Substance plug-in which the user _can_ disable too. Not sure if that's the way to go in the long run, but just FYI.
