### ISSUE TITLE
Houdini: Shelves Tools code broken

### ISSUE THREAD

**Issue by ddesmond** [ynput/OpenPype#4061]
**Running version**
3.14.6

**Describe the bug**
Houdini integration is not correctly implementing the shelf tools when using openpypes tools UI. The path to the script file is inserted instead of the script content. 
Name error is present becouse OP tried to check for "name" instead of label. Missing name in the tool output:
`('tool_definition', {u'label': u'desflip', u'icon': u'Z:/houdini/shelves/icons/dfm_flipbook.png', u'help': u'bla bla help', u'script': u'Z:/houdini/shelves/tools/dfm_flipbook.py'})`
Error itself:
```
  File "C:\_repos\OpenPype\openpype\hosts\houdini\api\shelves.py", line 74, in <genexpr>
    tool_definition[key] for key in mandatory_attributes
KeyError: ('name',)
```

**To Reproduce**
Create a shelf tool for Houdini in the Shelves UI in OpenPype.
Boot houdini, check for shelf.
Press the new shelf tool to start using it.
There will be first a name error and after this passes script will not be able to run becouse there is no script content in it.

**Expected behavior**
A press on the shelf button would yield code being executed and tool running.

**Screenshots**
![image](https://user-images.githubusercontent.com/2397041/199650854-777226dc-fe0d-44a2-bf8f-4ef3d44691b9.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Host: Houdini 19.0

[cuID:[OP-4355](https://app.clickup.com/t/31phtdx)]

**Comment by ddesmond** [comment]
We have a fix for this -  will submit a PR for it.  You can assign me on this one.

**Comment by BigRoy** [comment]
@ddesmond Any input on that fix from your end?

**Comment by ddesmond** [comment]
i will not be able to submit a new fix for this until late next week.
There was a PR for this issue but i cant find it

**Comment by BigRoy** [comment]
I think this issue has actually already been resolved. The original error has at least been fixed (`name` refactored to `label`) and I was able to generate a shelve here in latest develop. Closing the issue.
