### ISSUE TITLE
Resolve: Switching versions in timeline fails in Resolve 18

### ISSUE THREAD

**Issue by jrsndl** [ynput/OpenPype#4084]
**Running version**
3.14.7-nightly.1

**Describe the bug**

**To Reproduce**
1. Use Use Asset Loader to load latest version of more than one shot in the timeline
2. Use Manager (Scene Inventory) to switch version to older in two or more shots
3. Note that versions are correctly loaded in media pool, but only the first shot in the timeline is changed
4. Also note that Scene inventory shows wrong versions (still latest) after reopening

**Desktop (please complete the following information):**
 - OS: WIn10
 - Host: Resolve 18

[cuID:[OP-4393](https://app.clickup.com/t/32djr36)]

**Comment by jakubjezek001** [comment]
fixed via https://github.com/ynput/OpenPype/pull/5673
