### ISSUE TITLE
Maya: Render creator doesn't work with Deadline module turned off

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#4103]
## Bug

If Deadline module is disabled, render instance creator will crash on missing project settings.

This issue is caused by return statement here:

https://github.com/pypeclub/OpenPype/blob/b2e0cd846333cb455c69f0a5d61e51f4dfdf7a7f/openpype/hosts/maya/plugins/create/create_render.py#L76-L80

if Deadline is disabled, constructor will quit without initializing `_project_settings`. Connected to it is that availability of Deadline should not be determined by the settings, but from the modules manager.

[cuID:[OP-4422](https://app.clickup.com/t/334dthu)]

**Comment by BigRoy** [comment]
I believe this has been fixed. @LiborBatek can you confirm?

**Comment by BigRoy** [comment]
> First tested to create Render Instance when not running Deadline Web Service... which doesnt allow the user to create it with following error msg:

But this is still with the deadline module enabled? Even though the error message is explicit I'd say that if you have it enabled but can't access deadline that it raising errors is valid, right?

**Comment by LiborBatek** [comment]
So second test I did was with ```Deadline``` module ```Disabled``` in OP Settings and no error found.

User is able to create ```Render``` Instance without troubles...

**Comment by LiborBatek** [comment]
SO yeah it has been resolved already and is in latest OP. 

Can be Closed then?

**Comment by BigRoy** [comment]
@antirotor I'd say close it. Yes?

**Comment by kalisp** [comment]
Closing as it should be resolved. Please reopen if necessary.
