### ISSUE TITLE
Publishing: Register publishes without copying them

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#4130]
## Feature

For some types it is better to just register new version with OpenPype without copying it to final destination. For large caches, editorial stuff or even renders that are rendered directly there.

### Solution

The easiest way to do it would be to  add new template to anatomy, called *original location* or *source* or whatever. The you would set it for specific families via Settings or in the new publisher whether to use this or not. Publish will process it only by registering, maybe checking if its root is known - to prevent cases of publishing stuff that's only on artists computer. We already have concept of `originalBasename` token in Tray Publisher. We need to add it to the collectors dealing with already existing files (like editorial collectors and render collector on Deadline) plus adding `originalDirname` to the instance so template like `{originalDirname}/{originalBasename}.{ext}` could be used. With this, nothing else would need to be changed, loader should pick it up as usual.

[cuID:33vde1j]

**Comment by kalisp** [comment]
I think new schema is too late as during Create `Variant` from UI is created for subset creation. Which would be fine only for published items with `Main` in its name.
I think there should be new flag denoting that dragged item(s ?) is already in proper location with proper name. From this context could be parsed >> subset used >> publishable instance created. No need to select context from left column.
If toggle would be checked and dragged in file is in wrong location/wrong name/unable to parse/version already existing, instance will be created marked that is invalid. These instances would need to be dropped, file renamed, dragged again, recreated.
(Or maybe instance is not created, but dialog with list of broken items is provided).
![Screenshot 2022-11-30 165538](https://user-images.githubusercontent.com/4457962/204849226-9728697a-6b07-465b-b50e-54de9658f161.png)

(And I am talking about Tray Publisher and creators from Settings for now.)

**Comment by kalisp** [comment]
Resolved by https://github.com/ynput/OpenPype/pull/4157
