### ISSUE TITLE
Hero version not downloaded/created when downloading a subset representation

### ISSUE THREAD

**Issue by Tilix4** [ynput/OpenPype#4154]
**Running version**
[ex. 3.14.1-nightly.2]

**Describe the bug**
Actual issue: When a representation is fetched by the sync server with all its dependencies, it does not fetch the hero version, while the representation's file might reference the hero version, which leads to broken libraries.

Minimal testing: Downloading a subset's representation doesn't download or recreate the hero version.

**To Reproduce**
1. Enable hero version in settings
2. Publish a subset
3. Make the subset not locally available
4. In Loader: Find the subset
5. Download a representation
6. The hero version is not available

[cuID:[OP-4544](https://app.clickup.com/t/37buk81)]

**Comment by kalisp** [comment]
Resolved by https://github.com/ynput/OpenPype/pull/4191
