### ISSUE TITLE
[openpype3] Ftrack task status does not automatically change after publishing from Nuke

### ISSUE THREAD

**Issue by BrightDay2510** [ynput/OpenPype#4179]
Hi, 
I am a newbie here and i am a user only. 
Is there anything that we need to set it up in Pype to have automatically task sync to Ftrack? 
For example, when the publish is done from Nuke, we have task in Ftrack changing from "in progress" to "pending review"
or this kind of thing ?

Thank you for helping!

[cuID:[OP-4565](https://app.clickup.com/t/37q67c6)]

**Comment by antirotor** [comment]
Hey,

this is done using [ftrack event server](https://openpype.io/docs/module_ftrack#event-server). Then it can be configured in the Settings - https://openpype.io/docs/module_ftrack#sync-status-on-first-created-version

![image](https://user-images.githubusercontent.com/33513211/212678626-ee36b9fa-6222-4f8c-9c4c-73e960ee079a.png)
