### ISSUE TITLE
Substance Painter & Substance Designer integration

### ISSUE THREAD

**Issue by kekefreedog** [ynput/OpenPype#4205]
Hello !

## Need

Do you planned to integrate Substance Painter & Substance Designer into OpenPype ?

## Ressources

https://www.adobe.com/fr/products/substance3d-painter.html

https://substance3d.adobe.com/documentation/spdoc/scripts-and-plugins-197427392.html

[cuID:[OP-4612](https://app.clickup.com/t/382ke3d)]

**Comment by BigRoy** [comment]
@kekefreedog As far as I'm aware there hasn't been huge community interest in a Substance Painter/Designer integration as of yet. It's nice seeing your request pop up and I hope there's more interest! :)

What particular features would you like in the integration?

- Workfiles support: save, open substance workfiles
- Launch Substance from OpenPype launcher
    - including start Substance with last workfile
- Importing published alembic models
- Exporting textures (and also publish them?)
- A published "package" for the textures to automatically be able to load import/load them for a renderer in a DCC of choice (massive undertaking likely)

### References

- [Shotgrid Toolkit Integration for Substance](https://community.shotgridsoftware.com/t/substance-designer-shotgun-toolkit-engine-released/9944)
- [Prism 2.0 Substance Integration Preview between 07:00 - 09:10](https://vimeo.com/551545616)

**Comment by kekefreedog** [comment]
Hi @BigRoy !

Your list is perfectly matching with our need.

Then it could be nice to have those additional features :
- Have a color management using OCIO
- When Publish texture, option for generate equivalent of `.tx` for some render engine (like Arnold...) 
- Generate material already connected to mesh
- Be able to export USD layer with material and its assignations

**Comment by BigRoy** [comment]
Those are some amazing stretch goals to the integration. Thanks for these notes - I don't expect these to be there for an initial integration but they are definitely nice-to-haves to look into once the bare necessities and first draft of the substance integration is tested.

**Comment by kekefreedog** [comment]
I definitely agree with you. First integration will be awesome for lots of studio. 
Then if my dev department has free time, they could be interesting for contribute to it !
Let's keep in touch.
Thx ;)

**Comment by BigRoy** [comment]
@kekefreedog I'm not sure if you had seen but I did a first prototype integration for Sustance Painter some time ago: https://github.com/ynput/OpenPype/pull/4283

It's not production-ready but any feedback is welcome of course. The biggest change that'll likely still need to be implemented is how texture files are output/published. (Like the naming conventions, etc.)

**Comment by BigRoy** [comment]
Substance Painter integration has been available for some while - but Substance Designer has not - I wonder whether it'd make sense to change this issue to remain about Substance Designer instead or create a new one solely dedicated to Substance Designer request.

@MustafaJafar thoughts?

**Comment by MustafaJafar** [comment]
> I wonder whether it'd make sense to change this issue to remain about Substance Designer instead or create a new one solely dedicated to Substance Designer request.

I agree Substance Painter and Designer are two different issue, lets change this issue to remain about substance designer

Converting substance painter for Ayon is already on our list.
