### ISSUE TITLE
Global: Update frames in latest version

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4213]
**Is your feature request related to a problem? Please describe.**
Sometimes production needs only update couple individual frames from already created version. This is including also updating any reviewable video / thumbnail files.

**Describe the solution you'd like**
This feature needs to be divided into several subtasks:
- Add instance attribute switch for updating latest version
- Add instance attribute frames selector, ex. `1010, 1105-1107, 1203`
- Anatomy temlate for studio wide staging dir which will be shared to all for intermediate folder. This will be used for collecting frames from latest version and rendering new frames into it. 
- Collector which will find all SiteSync files from latest version and its hashes
- Exctractor which will prepare complete representation data included latest version files for Reviewable exctractors
- there might be more.

**Additional context**
- reviewables version updating in Ftrack might be complicated.

[cuID:[OP-4617](https://app.clickup.com/t/382t6mw)]

**Comment by kalisp** [comment]
Resolved by https://github.com/ynput/OpenPype/pull/4362
