### ISSUE TITLE
Traypublisher: publishing version instance attribute

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4233]
**Is your feature request related to a problem? Please describe.**
We need to be able to define specific version on a subset. So we could lock it to only v001 for example. 

**Describe the solution you'd like**
Adding Instance attribute with future version (version above last found) used for publishing. If a user adds manually a version (1) it will override the existing version.

**Describe alternatives you've considered**
Since it is only `simple editorial` request, we could add this to subset attributes as it used to be in Standalone publisher. But we would still need to at least show to the user what version it will be published into, so again ideally in instance attributes.

[cuID:[OP-4646](https://app.clickup.com/t/861m3n941)]

**Comment by mkolar** [comment]
resolved by https://github.com/ynput/OpenPype/pull/5142
