### ISSUE TITLE
project key is not resolvable

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/OpenPype#4282]
**Is your feature request related to a problem? Please describe.**
I can't use a generic path for template builder with `project` key in settings in `project_settings/maya/templated_workfile_build/profiles/0/path`

`{root[work]}/{project[name]}/templates/template_model.ma`

```
# Error: KeyError: file D:\REPO\OpenPype\openpype\pipeline\workfile\workfile_template_builder.py line 713: "Could not solve key 'u'project'' in template path '{root[work]}/{project[name]}/templates/template_model.ma'" # 
```

static project name works fine
`{root[work]}/murphy_22101/templates/template_model.ma`

[cuID:[OP-4704](https://app.clickup.com/t/861m65v3b)]

**Comment by jakubjezek001** [comment]
solved in https://github.com/ynput/OpenPype/pull/4266
