### ISSUE TITLE
Subset Manager: Multi Selection

### ISSUE THREAD

**Issue by tokejepsen** [ynput/OpenPype#4294]
**Is your feature request related to a problem? Please describe.**
Be able to multi select in the subset manager.

**Describe the solution you'd like**
Would like to see multi selection in the subset manager so larger sets of instances can be cleared all at once.

[cuID:861m6jr5a]

**Comment by BigRoy** [comment]
> Be able to multi select in the subset manager.

Note. I suspect this tool will be dropped rather soon in favor of the new Publisher - since that internally allows to manage the scene's instances/subsets. Or is the Subset Manager about something else?

**Comment by tokejepsen** [comment]
That is a very good point! @iLLiCiTiT ?
