### ISSUE TITLE
Global subset name unique validator publish plugin

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4330]
Global plugin which validates this is the BEST case scenario since it's valid for basically ALL publishes - unless there are special cases I don't know about where two separate instances should somehow publish and integrate into the same asset+subset from within the same publish.

Here's an old basis for that logic: https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/global/publish/validate_unique_subsets.py

However as clearly can be seen from that todo it still has the bug that it doesn't check it per asset. I'd be happy to refactor it and set up a PR if we feel this is a worthwhile global plug-in.

_Originally posted by @BigRoy in https://github.com/ynput/OpenPype/pull/4308#discussion_r1071526144_
            

[cuID:[OP-4757](https://app.clickup.com/t/863fw69m7)]

**Comment by jakubjezek001** [comment]
Each instance, should have been able to store the validator disabled value into instance data - so in case user disable it on a instance with different asset name it will bypass the validator in next iterations of publishing.

**Comment by BigRoy** [comment]
> Each instance, should have been able to store the validator disabled value into instance data - so in case user disable it on a instance with different asset name it will bypass the validator in next iterations of publishing.

Please elaborate.

The validator itself should ignore subsets publishing to a different subset by default - that should totally be allowed. The validator should only invalidate whenever a publish of two instances in the scene go into the same **asset+subset**

**Comment by jakubjezek001** [comment]
> The validator itself should ignore subsets publishing to a different subset by default - that should totally be allowed. The validator should only invalidate whenever a publish of two instances in the scene go into the same asset+subset

Just to clarify some possible usecases and the validator outputs:
- one scene two the same subset names, each has different asset - **allow**
- one scene two the same subset names, each has the same asset = **invalid**

What if for some reason user will move scene content from one asset to another and forget about one subset. It will have the same subset name but different asset. Scene will be in v001 but the original scene were already in v005. So during publishing we will suddently hit an issue that validator will pass it as **allow**, but it could override the subset version, rigth?
