### ISSUE TITLE
Publisher: Access create tab after validation/publish

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4337]
**Running version**
[ex. 3.14.1-nightly.2]

**Describe the bug**

The Create tab gets disabled after validating/publishing but you can still access the tab by going to "Publish" and clicking on the + sign bottom left under the subsets. That's not too bad but it's quite confusing to be on that page with an error above.

![afbeelding](https://user-images.githubusercontent.com/2439881/213036013-ff74c281-d12d-4a05-9e9f-008a038bb6e4.png)

![afbeelding](https://user-images.githubusercontent.com/2439881/213036203-158fafa9-d911-4e5b-991b-341daea0b06f.png)

**To Reproduce**

1. Validate or publish
2. Go to publish tab
3. Click on + icon to create a new instance in the instance list
4. You're now on the greyed out "Create" tab.

**Expected behavior**

Either reset publishing when clicking on the + or disable the + icon like the tab.

[cuID:[OP-4761](https://app.clickup.com/t/861m8a062)]

**Comment by iLLiCiTiT** [comment]
Resolved by https://github.com/ynput/OpenPype/pull/4528
