### ISSUE TITLE
Nuke - create first workfile template switch to preset

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4355]
**Is your feature request related to a problem? Please describe.**
A New workflow template builder based on placehoder workflow doesn't support yet feature to create a first version automatically. 

**Describe the solution you'd like**
 The switch should be added to presets here `project_settings/nuke/templated_workfile_build` to have this on a preset rather than at the tool level. So for example **composting** can be activated **roto&paint** will be disabled.

**Additional context**
This is how it is done in older Templating workflow on the tool level
![image](https://user-images.githubusercontent.com/40640033/213431065-71571f84-e967-4e41-8f4a-5c528e0b931d.png)

[cuID:[OP-4778](https://app.clickup.com/t/863fwpqnf)]

**Comment by markandrewharris** [comment]
any fixes for this yet?

**Comment by jakubjezek001** [comment]
hey @markandrewharris we are starting on this one from next sprint, starting next week.

**Comment by markandrewharris** [comment]
Thanks

**Comment by jakubjezek001** [comment]
Developed and merged with https://github.com/ynput/OpenPype/pull/4579
