### ISSUE TITLE
Nuke - baking profiles reformat with a chain of multiple nodes

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4397]
**Is your feature request related to a problem? Please describe.**
We support only a single reformat properties for baking profiles. Some productions are demanding to expand the feature so multiple reformats could be chained to achieve desired image geometry.

**Describe the solution you'd like**
Settings preset should be rewritten so it supports multiple nodes inputs the same way as prenodes in Creator Render plugins are. API should be able to build chain of `repos` nodes (reformat, transform, crop) from a preset.

[cuID:[OP-4840](https://app.clickup.com/t/863fyzve8)]

**Comment by markandrewharris** [comment]
any fix fir this yet?

**Comment by jakubjezek001** [comment]
@markandrewharris this issue was resolved by https://github.com/ynput/OpenPype/pull/4514
