### ISSUE TITLE
Anchored publishing of sources with padding hashes duplication.

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#4502]
I have a problem loading published plate to Nuke. It looks like loadClip adds the hashes to read node path twice.

The plate name doesn't seem to make a difference. I have the same behavior with source plate named renderTest_v003.####.exr and boxed_mops_v003.Redshift_ROP1.####.exr

Plate published in Hiero 12.2v3, loading tested in Nuke 12.2v3 and 13.2v4

![PublishA](https://user-images.githubusercontent.com/45896205/219343926-fb7bd82f-39e5-4593-8df4-4cd015ea78a1.png)
![PublishB](https://user-images.githubusercontent.com/45896205/219344227-7176809e-da72-49a2-b487-3aa6bd3d4665.png)
![PublishC](https://user-images.githubusercontent.com/45896205/219347333-09720984-af8d-499d-8037-b6846fa05e65.png)

_Originally posted by @jrsndl in https://github.com/ynput/OpenPype/pull/4453#pullrequestreview-1301212274_
 

[cuID:[OP-4993](https://app.clickup.com/t/863g44guv)]

**Comment by BigRoy** [comment]
@jakubjezek001 @jrsndl is this issue resolved with https://github.com/ynput/OpenPype/pull/4503 ?
