### ISSUE TITLE
Launcher doesn't show other app versions

### ISSUE THREAD

**Issue by TonyHeadband** [ynput/OpenPype#4508]
**Running version**
3.15.2-nightly.1

**Describe the bug**
Can't see the other versions of the app that I've set up in the settings, plus Unreal is enabled but it doesn't show up

**Desktop (please complete the following information):**
 - OS: Windows

![image](https://user-images.githubusercontent.com/41022017/220701926-ef53c705-1d0a-4548-9230-f14b580b5b1e.png)

[cuID:[OP-4999](https://app.clickup.com/t/861mdgdtj)]

**Comment by BigRoy** [comment]
> Can't see the other versions of the app that I've set up in the settings, plus Unreal is enabled but it doesn't show up

Have you added them to the Project Settings in anatomy too? It'd be [around here in the documentation](https://openpype.io/docs/admin_settings_project_anatomy#attributes).

Basically:

1. System Settings defines all global applications/tools available in pipeline
2. The project anatomy defines which of those applications/tools are active for that project.

**Comment by BigRoy** [comment]
@TonyHeadband have you been able to resolve your issue since? Knowing where you currently stand would help us to decide whether this issue is worth keeping open.

I can't reproduce the issue on my end - taking into consideration the notes I posted in [my previous comment](https://github.com/ynput/OpenPype/issues/4508#issuecomment-1441430234).

**Comment by TonyHeadband** [comment]
Sorry, didn't see the msg.
I've create a new project after I've seen this comment and still blender as the version that I've set is not present.
![image](https://user-images.githubusercontent.com/41022017/224512375-21d49833-d0b6-40e0-b476-d7f5d699299e.png)

**Comment by BigRoy** [comment]
Could you show the Project Settings? At the top of Project Settings, there is Project Anatomy which contains Attributes > Applications.

You'll need to enable blender for the project.
Also, your screenshot is showing "Local Settings". I'm referring to the Admin > System Settings or something like that. 

_Due to a bug it's quite a slow interface just so you know but it's the one you'll need._

**Comment by TonyHeadband** [comment]
Oh yeah!
Between all the movie attributes(frame, clip, handle, resolution) I didn't see the application one, when I've enabled them there they showed up.
Silly me :)
Thank you
