### ISSUE TITLE
Maya: Arnold Scene Source (ASS) publish fails

### ISSUE THREAD

**Issue by LiborBatek** [ynput/OpenPype#4535]
Running ver. 3.15.2. Nightly2

When trying to publish ```Arnold Standin``` OP gives validation errors:

![image](https://user-images.githubusercontent.com/112623825/221599859-4d5b0500-66c8-4671-ad03-6f8ffe28ffaa.png)

So unable to publish anything as .ASS now

```

Instance: 
assMain
Message: 
'NoneType' object is not iterable
Line: 
39
Traceback: 
Traceback (most recent call last):
  File "D:\REPO\OP_3\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OP_3\openpype\hosts\maya\plugins\publish\validate_arnold_scene_source.py", line 48, in process
  File "D:\REPO\OP_3\openpype\hosts\maya\plugins\publish\validate_arnold_scene_source.py", line 39, in _get_nodes_data
TypeError: 'NoneType' object is not iterable

```

[cuID:[OP-5023](https://app.clickup.com/t/861me1da4)]

**Comment by tokejepsen** [comment]
@LiborBatek what does the objectset setup look like?
Looks like it cant find anything under the `content_SET`.

**Comment by LiborBatek** [comment]
I have tried to put top most hiearchy group node like ```model_GRP``` containing all the geometry(ies) and then also tried to put to ```content_SET``` just the ```geometry``` itself it didnt work for both cases...

so it was not empty of course. @m-u-r-p-h-y  had the same experience as he wrote on discord

**Comment by tokejepsen** [comment]
@LiborBatek to replicate your setup, could you give me some testing notes?

**Comment by LiborBatek** [comment]
1. Just create some geometries put them into group
2. create ```ass``` instance with ```use selection``` on during creation
3. try to publish ASS

The instance wont get properly validated and gives metioned err message (see srcn at the top)

My scene looks like this before I try to ```publish``` ```arnold scene source``` 

![image](https://user-images.githubusercontent.com/112623825/222086507-37ca5bf1-f380-485a-8c29-09f8e741fc8b.png)
