### ISSUE TITLE
The Output Image Format, always defaults to exr over in Maya for Vray

### ISSUE THREAD

**Issue by lucanvisuals** [ynput/OpenPype#4565]
**Running version**
3.15.1

**Describe the bug**
The Output Image Format, always defaults to exr over in Maya for Vray.
Path: project_settings/maya/RenderSettings/vray_render/image_format/

**To Reproduce**
1. Go to Maya
2. Set Vray as render engine
3. Apply render settings
4. The Image Format always defaults to 'exr' no matter what.

**Expected behavior**
It should be using the entries from OP project settings

**Screenshots**
![op_image_format](https://user-images.githubusercontent.com/104215675/222668102-e5396ef0-0bd9-4a3b-88f7-63b9c6bc6043.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Host: Maya 2022.4, Vray 6

[cuID:[OP-5167](https://app.clickup.com/t/863g6ec71)]

**Comment by BigRoy** [comment]
I believe the issue is [here](https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/maya/api/lib_rendersettings.py#L338-L339).

It should likely be something like:
```python
        # Set render file format to exr
        ext = vray_render_presets["image_format"]
        cmds.setAttr("{}.imageFormatStr".format(node), ext, type="string")
```

**Comment by m-u-r-p-h-y** [comment]
Redshift is affected as well

**Comment by BigRoy** [comment]
@m-u-r-p-h-y in what way is Redshift affected?

According to [this logic here](https://github.com/ynput/OpenPype/blob/173ec225eba1262de024e30917673d4650feb1ee/openpype/hosts/maya/api/lib_rendersettings.py#L210-L215) it seems you should be able to set any of the image formats in that list. Is that an inaccurate list?

**Comment by m-u-r-p-h-y** [comment]
![image](https://user-images.githubusercontent.com/352795/223155416-89138db9-2878-4fc1-a16c-c6c475607604.png)

everything is set but the format . .

**Comment by BigRoy** [comment]
Reopening this just to still look into why or why not it works for Redshift.

@m-u-r-p-h-y 
In that scene after trying to set the render setting with Redshift:
- Do you have any errors in the script editor?
- What does printing the value from redshift return?
```python
from maya import cmds
print(cmds.getAttr("redshiftOptions.imageFormat"))
```
- What happens if you run this to try and set the index yourself?
```python
from maya import cmds
cmds.setAttr("redshiftOptions.imageFormat", 1) # exr
# and then maybe after try this..
cmds.setAttr("redshiftOptions.imageFormat", 4) # tga
```

**Comment by BigRoy** [comment]
@m-u-r-p-h-y Could you report back about the redshift issue?
