### ISSUE TITLE
Merge all review tags into one

### ISSUE THREAD

**Issue by EmberLightVFX** [ynput/OpenPype#4569]
Currently we have 3 different review tags. `ftrackreview`, `shotgridreview` and `kitsureview`.
I don't see a reason why we would have 3 different review tags instead of just one.

Maybe there are some extreme edge-case where a production uses two of theses review tools but I have never heard about it myself.
Thoughts?

[cuID:[OP-5182](https://app.clickup.com/t/861mer10j)]

**Comment by BigRoy** [comment]
Should we still somehow keep `review-upload` tag separate from `review` itself? Or should we just always upload a review by default?

**Comment by EmberLightVFX** [comment]
> Should we still somehow keep a `review-upload` _(just as example; replacement for the 3 tags you mentioned)_ tag separate from `review` itself? Or should we just always upload a review by default?

That's a good question.

I myself have never bin in a situation where I haven't uploaded a review file so I would say always upload a review. 

What about you?

**Comment by Tilix4** [comment]
IMO `review` is sufficient. Review means "to be looked at by who is supposed to", therefore it must be uploaded to every production tracker we find.

**Comment by iLLiCiTiT** [comment]
Just to note, we have use-cases when something is marked as review so ExtractReview can create outputs but not all outputs are uploaded to "manager". So I disagree that `"review"` and `"ftrackreview"` are interchangeable.

Ad merging them, I think that @mkolar have an opinion on that front.

**Comment by EmberLightVFX** [comment]
I can see that the solo `review` tag should separated but `ftrackreview`, `shotgridreview` and `kitsureview` could be merged into one. Maybe rename it to something like `Upload to review platform` to really show what the tag does.

**Comment by Tilix4** [comment]
Things are becoming clearer 🥳  I'd have proposed the same thing as @EmberLightVFX does.

**Comment by BigRoy** [comment]
If there's a better preference than `review` + `review-upload` tags let me know @mkolar so I can maybe try and tweak the #4757 PR accordingly.

**Comment by EmberLightVFX** [comment]
`create-reviewable` and `review upload` sounds good to me

**Comment by iLLiCiTiT** [comment]
Note: If we'll do any of these changes it should go to release branch and not to develop.

**Comment by Tilix4** [comment]
I suggest tags should have different syntax from families, therefore @EmberLightVFX's proposal looks perfect to me (not having a `review` tag, which is very confusing)

**Comment by BigRoy** [comment]
@mkolar are you able to share your thoughts about this?

**Comment by mkolar** [comment]
Guys this might seem like its simplifying something, but it would take functionality that is crucial at the moment away. Hence I'm moving it to discussions for posterity, but don't see it as an issue.
