### ISSUE TITLE
Global: OpenPype fails to launch if environment has value with { } tokens

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4608]
**Running version**

3.15.2-nightly.6
_but the issue has been present for a long time_

**Describe the bug**

Launching OpenPype with an environment variable in your local environment containing a value with `{ }` tokens will fail to launch OpenPype.

The error (from an older version):
```python
~ ./openpype_gui 
>>> run disk mapping command ...
>>> Logging to server is turned ON
*** Cannot get OpenPype path from database.
>>> Finding latest version with [ 3.14.6 ]
  - booting version: 3.14.6
>>> Injecting OpenPype version to running environment  ...
>>> Validating version [ /mnt/apps/software/openpype/openpype-3.14.6 ]
--- version is valid
>>> loading environments ...
  - for Avalon ...
  - global OpenPype ...
Traceback (most recent call last):
  File "/mnt/apps/software/openpype/openpype-3.14.6/dependencies/acre/lib.py", line 48, in partial_format
    f = formatter.vformat(s, (), mapping)
  File "/root/.pyenv/versions/3.7.12/lib/python3.7/string.py", line 190, in vformat
  File "/root/.pyenv/versions/3.7.12/lib/python3.7/string.py", line 200, in _vformat
ValueError: unexpected '{' in field name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openpype/.venv/lib/python3.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 113, in run
  File "/opt/openpype/.venv/lib/python3.7/site-packages/cx_Freeze/initscripts/Console.py", line 15, in run
  File "start.py", line 1214, in <module>
  File "start.py", line 1122, in boot
  File "start.py", line 290, in set_openpype_global_environments
  File "/mnt/apps/software/openpype/openpype-3.14.6/dependencies/acre/core.py", line 76, in compute
    env[key] = lib.partial_format(env[key], data=data)
  File "/mnt/apps/software/openpype/openpype-3.14.6/dependencies/acre/lib.py", line 55, in partial_format
    f = re.sub(m, m.format(**data), f)
ValueError: Sign not allowed in string format specifier
```

##### Linux

This is something which can quite trivially happen on Linux due to storing BASH functions in the environment being explained in this [OP discord thread](https://discord.com/channels/517362899170230292/1042791013548314635).

E.g. a function could be exported like:
```bash
function restartworker { /opt/Thinkbox/Deadline10/bin/deadlinecommand RemoteControl `hostname -i` LaunchSlave `hostname -s`;}
export -f restartworker
```

Resulting in environment variable value of:
```bash
BASH_FUNC_restartworker%%=() {  /opt/Thinkbox/Deadline10/bin/deadlinecommand RemoteControl `hostname -i` LaunchSlave `hostname -s`;}
```

A workaround for this Linux issue could be clearing the environment of bash functions as you launch OpenPype:
```bash
for func in `declare -x -F | sed 's/declare -fx//'`;do unset -f $func;done && ./openpype_gui
```

**To Reproduce**
1. Set an environment variable like `myvar = hello {world}` or export a bash function in Linux like above.
2. Try and launch OpenPype and DCCs.

**Expected behavior**

It should be able to launch fine.

The local environment value should be ignored and not re-formatted. We should expect the value is written in a way that it was intended to be and if possible be left untouched.

**Additional context**

- [1st Report on Discord Thread by @Minkiu](https://discord.com/channels/517362899170230292/1042791013548314635)
    - [Also mentioned here](https://discord.com/channels/517362899170230292/890894521817260052/1084575730819661924)
- [2nd Report on Discord Thread](https://discord.com/channels/517362899170230292/1081349077989605457)

[cuID:[OP-5218](https://app.clickup.com/t/85zrrd366)]

**Comment by Minkiu** [comment]
Based on this [SO answer ](https://stackoverflow.com/a/20259837)

> This feature is bash-specific, so a test for an exported shell function needs to do what Bash does. Experimentation and [source code](http://git.savannah.gnu.org/cgit/bash.git/tree/variables.c#n341) show that Bash recognizes an environment variable as a shell function at startup by the presence of a `() {` prefix in its value — if the prefix is missing, or even slightly altered, the variable is treated as an ordinary data variable.

Maybe we can clean up the env dict when starting the [compute function](https://github.com/BigRoy/acre/blob/master/acre/core.py#L42) in `acre`, something like:

```py
env = env.copy()
env = {
    key: value,
    for key, value in env.items() 
     if not value.startswith('() {')
}
```

**Comment by BigRoy** [comment]
This bug was hit again recently, [reported here on discord](https://discord.com/channels/517362899170230292/890894521817260052/1143892584528351282).

**Comment by Minkiu** [comment]
This has now been [merged](https://github.com/ynput/acre/commit/5f55105deafd79165a4b59780475de82c06184e9) in the `ynput/acre` fork, so unless you want to keep it for `acre` (upstream) we can close this issue.

**Comment by BigRoy** [comment]
Would anyone be able to reproduce this still in Linux with AYON? @iLLiCiTiT do you know?

**Comment by iLLiCiTiT** [comment]
> Would anyone be able to reproduce this still in Linux with AYON? @iLLiCiTiT do you know?

I did see that env on one of our linux test machines, and I don't think it caused errors. Should be easy to reproduce on windows, just set some env variable to `() {  /opt/Thinkbox/Deadline10/bin/deadlinecommand RemoteControl `hostname -i` LaunchSlave `hostname -s`;}`

**Comment by BigRoy** [comment]
> > Would anyone be able to reproduce this still in Linux with AYON? @iLLiCiTiT do you know?
> 
> I did see similar env on one of our linux test machines, and I don't think it caused errors. Should be easy to reproduce on windows, just set some env variable to `` () { /opt/Thinkbox/Deadline10/bin/deadlinecommand RemoteControl `hostname -i` LaunchSlave `hostname -s`;} ``

![image](https://github.com/user-attachments/assets/a022b280-ae13-4cb4-aacd-7ea9c1b96c0a)

With this env var set I ran launcher (which you can see being present here in console as well)...
It launches e.g. Maya and Fusion just fine.

Seems to work. Closing.
