### ISSUE TITLE
Missing Local Settings documentation.

### ISSUE THREAD

**Issue by tokejepsen** [ynput/OpenPype#4620]
**Is your feature request related to a problem? Please describe.**
Missing `Local Settings` documentation here `admin_settings_local`.

[cuID:[OP-5228](https://app.clickup.com/t/85zrrmu4r)]

**Comment by tokejepsen** [comment]
Move local settings documentation as well

![Capture](https://user-images.githubusercontent.com/1860085/224992578-60bcd79d-28de-4d77-84ca-500389e33a68.PNG)

**Comment by mkolar** [comment]
This is all changing in AYON, so I'm closing the issue
