### ISSUE TITLE
Standalone: Unchecking "Next Available Version" has no effect

### ISSUE THREAD

**Issue by jeangjenq** [ynput/OpenPype#4636]
**Running version**
3.14.7

**Describe the bug**
While using the Standalone Publisher, unchecking "Next Available Version" and putting in a custom version number has no effect on the actual published version.

**To Reproduce**
1. Launch Standalone Publisher.
2. Select Job, Asset, Task and drag in any files to publish.
3. While "Next Available Version" is checked, note down the displayed version number.
4. Uncheck "Next Available Version", put in a much greater number in version box.
5. Hit publish.
6. Pyblish window will show it's attempting to publish as the original "Next Available Version", not the much greater number you put in.
7. Published files will have the original version number, instead of the much greater number you put in.

**Expected behavior**
Unchecking "Next Available Version" and putting in your custom version in Standalone Publisher should publish files as your custom version.

**Screenshots**
![image](https://user-images.githubusercontent.com/25937912/225446068-a7c59301-809d-4581-a239-4ed546064299.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Host: Standalone Publisher

**Additional context**
Did some digging.
in [widget_components](../blob/3.14.7/openpype/tools/standalonepublish/widgets/widget_components.py) up to `cli_publish`, the UI is reporting the correct custom version number. It dumps it in a json file, then after publishing, it read the json file to report back it has published your custom version. Regardless of what pyblish actually published. The json file is passed on as an env var called `SAPUBLISH_INPATH`.

But in pyblish, [collect_anatomy_instance_data](../blob/3.14.7/openpype/plugins/publish/collect_anatomy_instance_data.py) doesn't actually read the json file. It collects the instance data on its own, resulting in just publishing in "Next Available Version"

I updated [collect_anatomy_instance_data](../blob/3.14.7/openpype/plugins/publish/collect_anatomy_instance_data.py) from line 220 to this. 

```python
                latest_version = instance.data["latestVersion"]
                if latest_version is not None:
                    version_number += int(latest_version)

            # check for Standalone publisher custom version
            try:
                sa_publish = os.environ['SAPUBLISH_INPATH']
                sa_json = json.load(open(sa_publish))
                if sa_json['version']:
                    version_number = sa_json['version']
            except KeyError:
                pass

            anatomy_updates = {
                "asset": instance.data["asset"],
                "family": instance.data["family"],
                "subset": instance.data["subset"],
                "version": version_number
            }
```

Pyblish then attempt to detect the `SAPUBLISH_INPATH`, then read the version number in it, which has the intented custom version number from Standalone Publisher.

[cuID:[OP-5247](https://app.clickup.com/t/861mgvkp7)]

**Comment by antirotor** [comment]
Since Standalone Publisher is phased-out and replace by Tray Publisher, feel free to reopen the issue if it is still relevant there.
