### ISSUE TITLE
IntegrateAsset: Allows overwriting representations.

### ISSUE THREAD

**Issue by tokejepsen** [ynput/OpenPype#4656]
**Describe the bug**
When having two representations with the same resulting file name, the plugin does not fail.

**To Reproduce**
1. Setup the below extractor in the pipeline;
```python
from maya import cmds

from openpype.pipeline import publish


class ExtractExample(publish.Extractor):
    """Extract the content of the instance to an CPU cache file."""

    label = "ExtractExample"
    hosts = ["maya"]
    families = ["model"]

    def process(self, instance):
        staging_dir = self.staging_dir(instance)
        filename = "{}_gpu_cache".format(instance.name)

        # Write out GPU cache file.
        kwargs = {
            "directory": staging_dir,
            "fileName": filename,
            "saveMultipleFiles": False,
        }
        cmds.gpuCache(instance[:], **kwargs)

        if "representations" not in instance.data:
            instance.data["representations"] = []

        representation = {
            "name": "gpu_cache",
            "ext": "abc",
            "files": filename + ".abc",
            "stagingDir": staging_dir
        }

        instance.data["representations"].append(representation)

        self.log.info(
            "Extracted instance {} to: {}".format(instance.name, staging_dir)
        )
```
2. Setup model instance in Maya and publish.
3. Check the output representations, which should be; `.ma` and `.abc`. (Missing an additional `.abc`)

**Expected behavior**
The `IntegrateAsset` plugin should fail or at least warn developers about conflicting file names.

[cuID:[OP-5282](https://app.clickup.com/t/85zrt8xjq)]

**Comment by BigRoy** [comment]
Actually in this case. Are you sure the issue isn't already in the extractor overwriting the alembic file? Since both write to the same staging die, no?

**Comment by tokejepsen** [comment]
> Actually in this case. Are you sure the issue isn't already in the extractor overwriting the alembic file? Since both write to the same staging die, no?

Good point! Have modified the example plugin in the description, but the issue still stands.

> If the integrator still uses the [file transaction class I think it should already log a warning](https://github.com/ynput/OpenPype/blob/develop/openpype/lib/file_transaction.py#L85) already, right?

Yeah, it does actually log a warning, although I would argue its a slightly cryptic message and I personally would prefer for the plugin to fail in this case since we aim for the file its integrating to be immutable (?).
