### ISSUE TITLE
Review: Output as separate images for 'sequence of stills' instead of video

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4661]
**Is your feature request related to a problem? Please describe.**

When generating a reviewable output, like e.g. reviews from renders or reviews from playblasting in Maya it appears to be impossible to treat the output as a sequence of stills. (Or we couldn't find the setting/feature at least).

So basically a reviewable could output any of:
- A video file
- An image (a still)
- A sequence of images (multiple stills)

**Use case**

We sometimes produce multiple poses or stills in a single Maya scene to be able to quickly set up and render say 20 poses for a character. However, with the current review system the generated previews will always be a video file uploaded to e.g. Ftrack, etc.

Similarly a single frame reviewable would become a pretty insanely quickly looping video attachment on Ftrack. 

**Describe the solution you'd like**

It's hard to figure out exactly what would be the perfect solution. Becuase technically reviewing a video file and going frame by frame to e.g. draw notes over the poses would work fine (and maybe even better than reviewing 20 stills in some applications). 

However, it tends to become a slightly different story if those reviewables also need to pass the client's eyes since they are expecting to see stills and not a video file of 20 frames.

**Describe alternatives you've considered**

An alternative would be to set up separate instances where each instance is set to a single frame so they are considered to be just the image. Or to ignore that it's a video file and maybe share extracts of that for deliveries (or find the image output of e.g. a playblast and share that instead from disk)

[cuID:[OP-5293](https://app.clickup.com/t/861mhk7p3)]

**Comment by tokejepsen** [comment]
So the attribute option `Keep Images` on the objectset does not give you the functionality you need?

**Comment by BigRoy** [comment]
That would at least publish and store the separate images for a playblast in Maya, yes. (Does that also make its way to Ftrack? I'm not sure.)

But in this case I'm also talking about having colorspace corrected review output from e.g. playblasts but also renderlayers as images that would potentially also upload as images to Ftrack.

**Comment by tokejepsen** [comment]
> Does that also make its way to Ftrack? I'm not sure

Not the image themselves, only the review.

**Comment by tokejepsen** [comment]
> but also renderlayers as images that would potentially also upload as images to Ftrack

Are you not able to have a single frame render? Renders should get to Ftrack, but maybe its an issue with it being a movie at that point (?)

**Comment by BigRoy** [comment]
> Are you not able to have a single frame render? Renders should get to Ftrack, but maybe its an issue with it being a movie at that point (?)

Yes, the issue was mostly with it being a video. It's not a showstopper, but for e.g. a single frame it's definitely confusing that it's a video file both on Ftrack and offline.

Maybe the issue is somewhat related to also easily being able to ship a reviewable to a client - but maybe I'm mixing it too much with what's shown on Ftrack and what gets published.

**Comment by BigRoy** [comment]
Marking irrelevant with transition to AYON - feel free to reopen on relevant repo there if problematic issues arise nonetheless. (They are still videos there, but less problematic for us)
