### ISSUE TITLE
Photoshop: Refactor Collect Review to new publisher as Creator

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4679]
**Running version**

3.15.3-nightly.3

**Describe the bug**

The review instance for Photoshop still needs to be converted to use the Creator system of the new publisher. Currently the Instance gets generated _during_ publish and not during the new publisher's creator stage. As such, the review instance can't be toggled on/off in the publisher UI.

**To Reproduce**

1. Go to photoshop, starting publishing something.
2. It'll now always create a review instance during publish (if it's enabled in project settings)
3. The instance does not show before publishing and can't be enabled/disabled

**Expected behavior**

Allow enabling/disabling the instance.

If we want to have the instance always exist it should likely be generated similar to Workfile creator.

[cuID:[OP-5347](https://app.clickup.com/t/861mj3g57)]

**Comment by kalisp** [comment]
Closed by https://github.com/ynput/OpenPype/pull/4871
