### ISSUE TITLE
loader of fbx/abc camera from 3d

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#468]
**Describe the solution you'd like**
Add Loader plugin for loading fbx or abc camera into Comp

### depending on #452 

[cuID:PYPE-1357]

**Comment by BigRoy** [comment]
Loading Alembic through code in Fusion isn't trivial. In particular cameras isn't trivial as Fusion does come with a AlembicMesh3D node that does allow to load the Alembic. See:

- [WeSuckLess: Loading alembic cameras via script?](https://www.steakunderwater.com/wesuckless/viewtopic.php?f=6&t=1641)
- [WeSuckLess: Alembicscene import using python](https://www.steakunderwater.com/wesuckless/viewtopic.php?f=6&t=4555)

For solely loading geometry I might be able to supply an Alembic Mesh Loader if needed.
