### ISSUE TITLE
Maya: Extract Playblast in 2020.

### ISSUE THREAD

**Issue by tokejepsen** [ynput/OpenPype#4730]
**Running version**
develop

**Describe the bug**
Reported by @gabormarinov on [Discord](https://discord.com/channels/517362899170230292/517382145552154634/1090338762896195726).

Hi, I've found a bug regarding viewport settings and Maya 2020 (python2?). If project_settings/maya/publish/ExtractPlayblast/capture_preset/Viewport Options/override_viewport_options is set, then viewport setting for playblast fails.

```
Instance: 
modelProxy
Message: 
Cannot apply options Invalid flag ''
Plugin: 
pyblish.ExtractPlayblast
Path: 
C:\Users\gaborca\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.3-moonrock.1\openpype\vendor\python\common\capture.py
Line: 
748
Level: 
ERROR
Thread: 
MainThread
Millis: 
345.999956131
```

Playblast is extracted, but captured images are empty (Maya viewport is empty during extraction).

If I don't set project_settings/maya/publish/ExtractPlayblast/capture_preset/Viewport Options/override_viewport_options, then there is no error message, and the extraction works with the actual viewport settings as expected.

Bonus: Thumbnail extraction always fail with a similar message like above, I guess it always tries to override viewport settings.

I've attached two logs: one with viewport override on (which fails), and one without viewport override  (which is ok).
I've tried to further narrow down the problem, but I don't really have the tools or knowledge. Could you check it please, should create an issue?

In Maya 2022 the ˛project_settings/maya/publish/ExtractPlayblast/capture_preset/Viewport Options/override_viewport_options setting works ok.
The test was done with OP 3.15.3 in both Maya 2020 and 2022.

**To Reproduce**
@BigRoy investigated this more; https://github.com/ynput/OpenPype/pull/4531#issuecomment-1488194155

[cuID:[OP-5473](https://app.clickup.com/t/863gbt48b)]

**Comment by BigRoy** [comment]
This reproduces it as well:
```python
import capture
import json
print(capture)

data = r"""
{
    "viewport_options": {
        "backfaceCulling": false, 
        "cameras": false, 
        "clipGhosts": false, 
        "controlVertices": false, 
        "deformers": false, 
        "dimensions": false, 
        "displayLights": "default", 
        "displayTextures": true, 
        "dynamicConstraints": false, 
        "dynamics": false, 
        "fluids": false, 
        "fogging": false, 
        "follicles": false, 
        "gpuCacheDisplayFilter": false, 
        "greasePencils": false, 
        "grid": false, 
        "hairSystems": true, 
        "handles": false, 
        "headsUpDisplay": false, 
        "hulls": false, 
        "ikHandles": false, 
        "imagePlane": true, 
        "jointXray": false, 
        "joints": false, 
        "lights": false, 
        "locators": false, 
        "manipulators": false, 
        "motionTrails": false, 
        "nCloths": false, 
        "nParticles": false, 
        "nRigids": false, 
        "nurbsCurves": false, 
        "nurbsSurfaces": false, 
        "particleInstancers": false, 
        "pivots": false, 
        "planes": false, 
        "pluginShapes": false, 
        "polymeshes": true, 
        "rendererName": "vp2Renderer", 
        "shadows": true, 
        "strokes": false, 
        "subdivSurfaces": false, 
        "textures": false, 
        "twoSidedLighting": true, 
        "useDefaultMaterial": false, 
        "wireframeOnShaded": false, 
        "xray": false
    }
}
"""

preset = json.loads(data)
with capture._applied_viewport_options(preset["viewport_options"], "modelPanel1"):
    pass     
```
