### ISSUE TITLE
Documentation: Hero versions

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please state which of feature you have in mind and describe what are its shortcomings?

Hero versioning isn't documented.

### How would you imagine the enhancement of the feature?

Document:

- What is a hero version?
- Pros and cons of hero versioning.
- How to enable/disable hero versioning.

Maybe also mention how the feature might have been called in other pipelines, e.g. 'master version's or 'live version's or whatever is common but different terminology for the feature.

Maybe also show an example of how to switch between hero version and a specific version in the Loader.

Maybe describe the difference between a push versus pull pipeline.

### Is there any more labels you wish to add?

- [X] I have searched labels and added any

### Additional context:

Issue [came up on Discord here](https://discord.com/channels/517362899170230292/563751989075378201/1095212355702501447)

[cuID:[OP-5587](https://app.clickup.com/t/863gf2yrq)]

**Comment by BigRoy** [comment]
This PR https://github.com/ynput/OpenPype/pull/4838 adds hero versions to the Key Concepts / Glossary. I wonder however if we need more dedicated documentation for hero versions since that PR only covers a succinct explanation on **What is a hero version?**

**Comment by BigRoy** [comment]
Here's some example documentation that I think would be good to add - but I'm not entirely sure where:

```markdown

# Hero versions

### What is a hero version?

In a production pipeline a hero version is a versioning strategy where the latest published version (e.g. of a model or render) is automatically overwritten in-place, rather than being assigned a new version number like regular versions. This means that the hero version is always the latest version. As such, scenes loading that version will instantly update to this new version as it gets overwritten.


:::tip Push versus pull pipeline
The **Hero version** strategy is also known as a "push" pipeline because the new version of the asset is "pushed" to replace the older version, rather than requiring users to manually "pull" in the latest version.
:::

The use of a hero version strategy can help ensure that everyone is automatically using the latest version of a subset. However, automatically updating would also mean that if a machine was currently rendering a scene for which a new pointcache would be published that mid-render it would get the new updated pointcache resulting in a change of version as frames are being rendered.

### Configuring versioning

#### Enabling/disabling hero versions

Hero versions are an optional feature in OpenPype. They can be completely disabled by the admin in the Project Settings.

#### Publish version to match workfile version

The studio admin can also enable a feature where published version numbers follow the workfile version, so that for example a `workfile_v044` publishes to `v044` even if there is not yet a `v043`.

#### Version padding

The amount of padding a published version gets on the file system is based off of the anatomy template system. This setting can be found at `project_anatomy/templates/defaults/version_padding`.

:::note Version padding 
Note that the OpenPype tools like the loader will always display the versions with a padding of three. For example `v003`, even if your anatomy template is customized to writes the file with a padding of four like `v0003`.
:::

```

With https://github.com/ynput/OpenPype/pull/4455 we might also want to add the versioning from v000 under the **Configuring versioning** header (which might need to be in admin docs where the first part might be somewhere in artist docs?)

**Comment by mkolar** [comment]
@BigRoy I've added your more detailed description of hero versions into the ayon docs here https://github.com/ynput/ayon-documentation/pull/75

The other half about configuring versioning is great and We should probably make a new page in the admin/configuration section in the docs
