### ISSUE TITLE
Houdini: Unmanaged colorspaces in review ROP

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#4833]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Review OpenGL ROP node introduced by #3839 is not handling colorspaces correctly in regards to selected output format. If set to for example PNG, gamma correction will stay by default as 1, resulting in dark and incorrect review video.

### How would you imagine the implementation of the feature?

We should probably define mapping between gamma and file formats if possible, something like:

```python
{
	"png": 2.2,
    "exr": 1.0,
    "jpg": 2.2
}
```

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Describe alternatives you've considered:

This is probably solved by using "proper" color management like OCIO as implemented here #4700, but in case studio isn't using OCIO at all, this might be issue. Maybe validator with repair action should handle this.

[cuID:[OP-5600](https://app.clickup.com/t/861mn6q1x)]

**Comment by MustafaJafar** [comment]
This [PR](https://github.com/ynput/OpenPype/pull/5322) was made to solve this issue. 
as this PR was merged I believe this issue should be close. 
if the mentioned PR didn't solve the issue, feel free to reopen it.
