### ISSUE TITLE
Bug: Houdini Review instance without valid camera errors on collect review data

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

The publishing for a Houdini review instance will fail with "It is not your fault" whenever you have no valid camera set on the review node.

![image (1)](https://user-images.githubusercontent.com/2439881/233102802-0ae7123c-3813-46ad-a754-12e128786c6d.png)
![image](https://user-images.githubusercontent.com/2439881/233102805-0affda48-c219-41b6-9f30-3ce439a481e5.png)

### Expected Behavior:

The collectors should run fine and a validator should capture the issue with a nice validation report.

### Version

3.15.4-nightly.3

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Create review instance, do not set a valid camera
2. Run publish.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-5757](https://app.clickup.com/t/861mp7jd4)]

**Comment by antirotor** [comment]
This gets slightly more complicated when you switch it to LOPs mode. Then the camera parameter changes to `cameraprim` and is expected to hold camera primitive from stage.

It does work in slightly convoluted way that if you use **import camera prim** in object level and set it to OpenGL node as camera before switching it to LOPs mode, the collector will still collect proper camera attributes even though it comes in from unexpected way. I am not sure if there is easy way to get the same attributes we are getting from camera node from the camera primitive.

**Comment by BigRoy** [comment]
Thanks, you are right. 

I hadn't even seen on the OpenGL node you could set it to LOPs too, that's perfect. I'd say it's a separate issue from this one but supporting LOPs should definitely be on the todo list. We definitely shouldn't be importing camera to object level since it just means we're not evaluating it in LOPs.
