### ISSUE TITLE
Enhancement: Houdini: Support HDA publishing from non-object level

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4880]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

It seems that HDA publishing only works from `/obj` or at least from object level. Publishing a network in `/obj/geo1` seems to fail for one of our artists and reading the documentation he's not sure why. It doesn't mention anything about only being able to publish object level networks.

Here are the errors and [documentation](https://openpype.io/docs/artist_hosts_houdini#publishing-houdini-digital-assets-hda):

![image (5)](https://user-images.githubusercontent.com/2439881/233388704-852accaf-ffac-432d-a107-4de9036472ab.png)
![image (6)](https://user-images.githubusercontent.com/2439881/233388707-4055490e-d359-4206-9cc0-a017ac284c1d.png)

### How would you imagine the implementation of the feature?

Allow any subnet to be published as HDA maybe, like e.g. from `SOPs` context? Or at least improve the documentation to explain from where you are able to generate an HDA and improve the error message too.

It also feels slightly weird maybe that it's failing during Create?

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[OP-5762](https://app.clickup.com/t/861mpd5eu)]

**Comment by krishna8008** [comment]
This is a great help,

1.
We loosing the additional parameters added on HDA when publishing, Is it possible to keep the parameters same when publishing?
2. If some nodes inside HDA's will depend on obj level nodes, loading them in AVALON CONTAINER, might break, also the naming of HDA changing when loaded, can we lock the HDA name just like when it created
