### ISSUE TITLE
Enhancement: 3dsmax rendering time data from instance

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#4907]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

3dsmax rendering should take time data from instance (current scene settings) rather then from context (asset data). Without it, artist can't render arbitrary frame ranges. 

### How would you imagine the implementation of the feature?

It should behave as with other hosts, where render instance has data collected from current scene settings and there is optional frame range validator that checks if frame range is matching the one on context (asset data).

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[OP-5808](https://app.clickup.com/t/861mqa938)]

**Comment by antirotor** [comment]
This is now correctly implemented in #4914 but it is missing additional type of frame ranges:

What we need to add though is support for the `Frames` and for `Every Nth Frame`. This is handled with `rt.rendPickupFrames` for the *Frames* and `rt.rendNThFrame` respectively.

**Comment by moonyuet** [comment]
> This is now correctly implemented in #4914 but it is missing additional type of frame ranges:
> 
> What we need to add though is support for the `Frames` and for `Every Nth Frame`. This is handled with `rt.rendPickupFrames` for the _Frames_ and `rt.rendNThFrame` respectively.

The implementation in #4914 also changes the type to pick up the frame range. It is no longer handled with rt.rendPickupFrame but instead the range. 
![image](https://github.com/ynput/OpenPype/assets/64118225/7031c79a-1cfc-4f17-86a8-58f70b82aca9)
if we need to support this, we need to have really specific method to do so.

**Comment by antirotor** [comment]
Yes, I mean for now it is perfectly ok to use *Range*, but we will need to implement `rt.rendPickupFrame` too because the client is using it.

**Comment by moonyuet** [comment]
> Yes, I mean for now it is perfectly ok to use _Range_, but we will need to implement `rt.rendPickupFrame` too because the client is using it.

maybe I can use back the rt.rendPickupFrame for the client's needs. it's not hard to fix
