### ISSUE TITLE
Unreal: Updating version of layout fails

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#4936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When layout is loaded in Unreal, we can't switch between its versions. Most probably coming from renaming.

### Expected Behavior:

Switching versions should work.

### Version

3.15.6

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Load layout into Unreal
2. Try to switch version of it
3. Nothing will happen except the traceback

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "D:\REPO\OpenPype\openpype\tools\sceneinventory\view.py", line 248, in <lambda>
LogPython: Error:     lambda: _on_update_to_latest(items)
LogPython: Error:   File "D:\REPO\OpenPype\openpype\tools\sceneinventory\view.py", line 232, in _on_update_to_latest
LogPython: Error:     update_container(item, -1)
LogPython: Error:   File "D:\REPO\OpenPype\openpype\pipeline\load\utils.py", line 486, in update_container
LogPython: Error:     return loader.update(container, new_representation)
LogPython: Error:   File "D:\REPO\OpenPype\openpype\hosts\unreal\plugins\load\load_layout.py", line 822, in update
LogPython: Error:     layout_level = levels[0].get_editor_property('object_path')
LogPython: Error: Exception: AssetData: Failed to find property 'object_path' for attribute 'object_path' on 'AssetData'
```

[cuID:[OP-5877](https://app.clickup.com/t/863gnrze2)]

**Comment by simonebarbieri** [comment]
They removed the `object_path` property from `AssetData` in 5.1... I found it out while working on #4075 and fixed it there. I'll fix it for current release as well!
