### ISSUE TITLE
Bug: Representations right click error - 3.15.6-nightly.1 next-minor

### ISSUE THREAD

**Issue by Jeremyball** [ynput/OpenPype#4949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Right click on subset produces an error.

### Expected Behavior:

Produce a list of available representations.

### Version

3.15.6-nightly.1

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Created new project on Ayon Server

In Editor Tab
- Create folder assets
- Create asset 
- Create modeling task

![image](https://user-images.githubusercontent.com/54645515/236957346-7bec9722-5193-42af-94cf-fa7234319093.png)

Launch Maya via Launcher

- Create sphere - ball_GEO
- Grouped under geo_GRP 
- Create modeling publish
- Add geo_GRP to set
- Publish(all checks green, publish is good)

New Maya scene

- Loader
- Navigate to asset
- Right click subset
- No menu - error

![image](https://user-images.githubusercontent.com/54645515/236957608-d6c1a29d-c980-4f51-af1e-f08659fce826.png)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
# Traceback (most recent call last):
#   File "E:\ayon\OpenPype-release-next-minor\build\exe.win-amd64-3.9\openpype\tools\loader\widgets.py", line 481, in on_context_menu
#     self._repre_contexts_for_loaders_filter(items)
#   File "E:\ayon\OpenPype-release-next-minor\build\exe.win-amd64-3.9\openpype\tools\loader\widgets.py", line 350, in _repre_contexts_for_loaders_filter
#     for repre_doc in repre_docs:
#   File "E:\ayon\OpenPype-release-next-minor\build\exe.win-amd64-3.9\openpype\client\server\entities.py", line 502, in get_representations
#     fields = representation_fields_v3_to_v4(fields, con)
#   File "E:\ayon\OpenPype-release-next-minor\build\exe.win-amd64-3.9\openpype\client\server\conversion_utils.py", line 603, in representation_fields_v3_to_v4
#     fields |= {
# TypeError: unsupported operand type(s) for |=: 'list' and 'set'
```

### Additional context:

Windows
3.15.6-nightly.1 
Banch: release/next-minor
Maya 2023.2

[cuID:[OP-5881](https://app.clickup.com/t/861mrwpjf)]

**Comment by sjt-rvx** [comment]
I ran into the same thing, got it working with small changes to `openpype/client/server/conversion_utils.py` 
Haven't gotten around to making this a real fix.

```python
...
   if not fields:
        return None

    representation_attributes = con.get_attributes_for_type("representation")

    output = set()
    # my hack starts
    fields = set(fields)
    iterfields = fields.copy()
    for field in iterfields:  # replaced the line 'for field in fields:'
    # my hack ends
        if field in ("type", "schema"):
            continue

        if field in REPRESENTATION_FIELDS_MAPPING_V3_V4:
            output |= REPRESENTATION_FIELDS_MAPPING_V3_V4[field]
...
```

**Comment by BigRoy** [comment]
Just out of curiosity. Where is that file? I can't seem to find it in the repository source code.

**Comment by antirotor** [comment]
> Just out of curiosity. Where is that file? I can't seem to find it in the repository source code.

it is in `release/next-minor` so 3.15 is little misleading.

**Comment by Jeremyball** [comment]
Thanks! that works, menu and functions are working as expected. 
![image](https://github.com/ynput/OpenPype/assets/54645515/bc557ad2-8915-4bd8-bb10-0c8b91ad7e90)

**Comment by sjt-rvx** [comment]
I've created a pull request which incorporates this _fix_ (#4959)

**Comment by BigRoy** [comment]
Fixed in ayon :)
