### ISSUE TITLE
Bug: Ayon - maya - "Set Frame Range" fails due to keyerror

### ISSUE THREAD

**Issue by sjt-rvx** [ynput/OpenPype#4951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Running from the release/next-minor branch

Run the command from the menu, it fails with the message
# Error: KeyError: file /cache/dev/OpenPype/openpype/hosts/maya/api/lib.py line 2230: 'include_handles' # 

which points to that maya settings don't have an `include_handles` setting.

### Expected Behavior:

The framerange would be set to the values in the db.

### Version

3.15.6-nightly.1

### What platform you are running OpenPype on?

Linux / Centos

### Steps To Reproduce:

1. Run the release/next-minor branch,
2. Run maya from a shot
3. select "Set Frame Range"

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-5885](https://app.clickup.com/t/861mrzy84)]

**Comment by antirotor** [comment]
just tested in `3.17.5-nightly.2` and it seems it's working. Feel free to re-open if the issue remains.
