### ISSUE TITLE
Ayon Tray: Admin > Studio Settings item

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#5009]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

OpenPype has in Tray `Admin > Studio Settings` item that will open Settings. In AYON, we should keep it with changed functionality so the website with settings is opened in browser.

### How would you imagine the implementation of the feature?

For backwards compatibility it should be as simple as opening default browser with specific URL.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[OP-6024](https://app.clickup.com/t/861mupvd8)]

**Comment by mkolar** [comment]
This is not needed in AYON, considering we have the web UI. closing
