### ISSUE TITLE
Enhancement: multiple versions installed

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/OpenPype#5020]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

windows OP installer is removing records of current versions of OP installed.

- previous versions need to be removed manually

![image](https://github.com/ynput/OpenPype/assets/352795/1c5706f1-391f-4ff0-9558-665b9b9d63cd)

### How would you imagine the implementation of the feature?

- the installer should register each version and let the user uninstall specific version
- the installer should ask if you want to remove already installed version

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Additional context:

OS: Windows 

[cuID:[OP-6035](https://app.clickup.com/t/863gug4mm)]

**Comment by mkolar** [comment]
obsolete with AYON, closing
