### ISSUE TITLE
Bug: Maya Look Attribute for `aiSubdivType` fails to apply on assignment

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#5260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

With a published look with attribute values like:
```json
		"attributes": {
			"aiSubdivType": "catclark",
			"aiSubdivIterations": 6,
			"aiDispPadding": 0.0,
			"aiDispAutobump": true,
			"aiAutobumpVisibility": 97
		}
```
The look assigner fails to set the mesh attributes due to `aiSubdivType` being a string.

### Expected Behavior:

Look assignment should work with arnold attributes.

### Version

3.15.12-nightly.3

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Tested with Maya 2024.1 + Mtoa 5.3.2

To reproduce:
- Publish a look for a (referenced!) mesh with the arnold subdiv type set to `catclark`

![image](https://github.com/ynput/OpenPype/assets/2439881/ea25ff5c-10ee-44ff-bc3c-641b83e8cd2a)

- Assign the look on a new/fresh model - it fails on setting the attributes.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
# Traceback (most recent call last):
#   File "E:\openpype\OpenPype\openpype\hosts\maya\tools\mayalookassigner\app.py", line 280, in on_process_selected
#     assign_look_by_version(nodes, version_id=version["_id"])
#   File "E:\openpype\OpenPype\openpype\hosts\maya\api\lib.py", line 1730, in assign_look_by_version
#     apply_shaders(relationships, shader_nodes, nodes)
#   File "E:\openpype\OpenPype\openpype\hosts\maya\api\lib.py", line 1871, in apply_shaders
#     apply_attributes(attributes, nodes_by_id)
#   File "E:\openpype\OpenPype\openpype\hosts\maya\api\lib.py", line 1618, in apply_attributes
#     set_attribute(attr, value, node)
#   File "E:\openpype\OpenPype\openpype\hosts\maya\api\lib.py", line 1595, in set_attribute
#     cmds.setAttr(node_attr, value, type=attr_type)
# RuntimeError: setAttr: The attribute 'prop_cheese_bite_GESShape.aiSubdivType' does not accept data of type 'string'.
#
```

**Comment by tokejepsen** [comment]
Fixed with #5261
