### ISSUE TITLE
Bug: Multiselection combobox does not show check state with PySide6 on macos

### ISSUE THREAD

**Issue by movalex** [ynput/OpenPype#5313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

The multiselection combo shows empty boxes for active elements in the list.
It does not update check marks on mouse click.
It also crashes OpenPype on keyboard space press.

### Expected Behavior:

On a mouce click the checkmark should appear in the box. 
Pnce the combobox is opened, all active elements should be checkmarked

### Version

3.16.0

### What platform you are running OpenPype on?

MacOS

### Steps To Reproduce:

1. Open OP Admin settings on macos
2. Open anatomy-attributes-applications list and click on empty box, no check mark will appear
3. Select the box with a keyboard and press space, the OP will crash.

![image](https://github.com/ynput/OpenPype/assets/11698866/0d01bc82-941e-44ec-9600-7f530b740ec3)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-6377](https://app.clickup.com/t/861n2r90t)]

**Comment by mustafa-zarkash** [comment]
I can notice that the mentioned PR is merged, Is this issue still open ?

**Comment by movalex** [comment]
I will close it, thanks!
