### ISSUE TITLE
Bug: Houdini settings are hardcoded

### ISSUE THREAD

**Issue by mustafa-zarkash** [ynput/OpenPype#5398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Houdini project settings are not used, however they are hard coded in plugins scripts. 

#### Arnold ASS Extension 
![image](https://github.com/ynput/OpenPype/assets/20871534/870efd94-9a72-4286-bccf-79ce13b949ab)

It's hard coded in `create_arnold_ass.py`

https://github.com/ynput/OpenPype/blob/20376655faba25002d4e0bc0f31e2c4cd0bd2bb3/openpype/hosts/houdini/plugins/create/create_arnold_ass.py#L16

Result
![image](https://github.com/ynput/OpenPype/assets/20871534/777000ea-2695-4397-a089-aa95fd117a5c)

#### ~~Validate Workfile Paths~~
 it's automated for validators, check this [comment](https://github.com/ynput/OpenPype/pull/5400#discussion_r1283008864)

![image](https://github.com/ynput/OpenPype/assets/20871534/c5cf80fd-606d-4698-bf35-83d236887b67)

### Expected Behavior:

Plugins should access houdini project settings to update instance data like in maya. 
e.g. 
add a method override
```python
    @classmethod
    def apply_settings(cls, project_settings, system_settings):
        """Apply project settings to creator"""
        settings = (
            project_settings["maya"]["publish"]["ValidateMayaUnits"]
        )
```

### Version

3.16.3-nightly.3

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. create an instance of `Arnold ASS` it won't change according to houdini project settings.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-6506](https://app.clickup.com/t/861n5ju95)]

**Comment by BigRoy** [comment]
> Plugins should access houdini project settings to update instance data like in maya, e.g. add a method override

Isn't the behavior that it applies from settings by default if the `apply_settings` override method is not implemented? I recall that being the case for Validators at least.

**Comment by mustafa-zarkash** [comment]
> I recall that being the case for Validators at least.

yeah, there are two places to add  `apply_settings`  
1. `Creator` which will set class attributes on creation 
2. Validator to read settings 

I'm going to make a PR shortly.
