### ISSUE TITLE
add custom icons to maya outliner items

### ISSUE THREAD

**Issue by mkolar** [ynput/OpenPype#54]
<i>[PYPE-605] created by admin</i>

[cuID:OP-1372]

**Comment by BigRoy** [comment]
Just posting these links so it's connected to this issue:
- [[Maya-Python] Custom Maya node, with iconName like dagContainer](https://groups.google.com/g/python_inside_maya/c/9XAzZL24tUs)
- [NodeSticker](https://github.com/davidlatwe/NodeSticker)

**Comment by tokejepsen** [comment]
@mkolar @antirotor Any further information about this?

What is the goal of adding this feature?

I can see maybe value with adding custom icons to data holding nodes like objectsets, but exposing some settings to a studio admin I'm not sure where the value is added.

**Comment by tokejepsen** [comment]
@mkolar should we close this issue?
There is little gain to get from it and no clients have requested or supporting this feature.

**Comment by mkolar** [comment]
Yep truly unimportant
