### ISSUE TITLE
Houdini Shelves Manager: Shelf is not created without specifying shelf set name

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

In Houdini, Shelf creation doesn't require a shelf set name.
however Shelves Manager won't create a shelf without adding a `shelf set name`

![image](https://github.com/ynput/OpenPype/assets/20871534/6ddadb80-f09a-4b1f-a358-4829db9819b6)

### Expected Behavior:

Missing `Shelf set name` shouldn't stop shelf creation.

### Version

3.16.4-nightly.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. create a shelf by adding tools (like screenshot above)
2. Launch Houdini and try to find your new shelf
3. Alternatively, you can check `default.shelf` contents

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Additional context:

Here's an example script that you can use. 

```python
import hou 
hou.ui.displayMessage("Hello There!")
```

[cuID:[OP-6714](https://app.clickup.com/t/861najcuy)]

**Comment by mustafa-zarkash** [comment]
If you want to create shelf be adding tools, then you should add a `Shelf Set Name` to avoid this issue. 

![image](https://github.com/ynput/OpenPype/assets/20871534/7a856914-dccb-4a7b-8cfa-fedad786b97c)
