### ISSUE TITLE
Houdini Shelves Manager: pathes are not resolved if template keys are used 

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

paths are not resolved if template keys are used

![image](https://github.com/ynput/OpenPype/assets/20871534/68ed311a-c6c6-4e45-8b8f-505dc0950102)

### Expected Behavior:

Shelves manager should be able to resolve paths if template keys are used 

### Version

3.16.4-nightly.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Do the same as the screenshot above:
1. Create a shelf file
2. add it in houdini settings using template keys 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```
Shelf path doesn't exist - {root[configs]}\houdini\shelves\null_shelf.shelf
This path doesn't exist - {root[configs]}\houdini\scripts\say_hello.py
```

[cuID:[OP-6710](https://app.clickup.com/t/861najcbg)]

**Comment by mustafa-zarkash** [comment]
Use full path to avoid this issue. 
![image](https://github.com/ynput/OpenPype/assets/20871534/98038a65-3e6d-4b9b-be78-5f46334b477d)
