### ISSUE TITLE
Bug: Houdini HDA update or set version does not change version in scene inventory

### ISSUE THREAD

**Issue by krishna8008** [ynput/OpenPype#5478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When we update the HDA's in houdini using scene inventory to latest version, data is chaning which is good, but version number reamining same(v001) even after "n" no of publishes updated
![image](https://github.com/ynput/OpenPype/assets/61413765/ae6180e9-8b31-4ef5-ab82-2cc6c1ec580c)

### Expected Behavior:

version should upgrade when we updated the HDA to latest version in scene inventory

### Version

3.16.4-nightly.3

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

scene file 1 : Publish Any HDA in houdini
scene file 2 : Load in new scene file
scene file 1 : publish a another version adding changes
scene file 2 :  when you update the HDA to latest the version name in scene inventory is staying always as v001

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by krishna8008** [comment]
Just noticed, any New Loaded assets are also not listing in Inventory!

**Comment by krishna8008** [comment]
> 1. Does this only occur for HDAs or ALL loaded family types?
> 2. Do you see any errors reported in the Houdini console?

Hey @BigRoy ,

1. I've tested with other family types like, bgeo,abc they all are updating fine, I think the issue is only with the HDA! Seems like set version in scene inventory is also not working for HDAs.

2. Console doesn't show any errors in my side

**Comment by krishna8008** [comment]
Hey @moonyuet  Thanks for looking into this,

Can HDA be loaded with same name we created? this is a slightly a different issue than the discussion, but wanted to know the possibility of it

**Comment by moonyuet** [comment]
> Hey @moonyuet Thanks for looking into this,
> 
> Can HDA be loaded with same name we created? this is a slightly a different issue than the discussion, but wanted to know the possibility of it

I dont think so if you talk about just barely the same time(i.e. vdb_smooth and vdb_smooth1) I believe you can check manually in houdini by creating two same node and tried to rename them with the same time.
But it is possible to do test01_v001_:_vdb_smooth amd test01_v002_:_vdb_smooth.
