### ISSUE TITLE
Bug: Maya Repair Incorrect Frame Range Action fails / doesnt work

### ISSUE THREAD

**Issue by LiborBatek** [ynput/OpenPype#5495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When workfile containing wrong ```frame range``` on OP instances like ```Review``` ```Animation``` ```Pointcache``` differing from DB entries ```Validator``` ```Repair``` action does not set those accordingly. Practically fails to repair those ```frame ranges```.

![image](https://github.com/ynput/OpenPype/assets/112623825/7897845f-f490-478d-88fc-6eec0bef9292)

And the log for the error when user triggered Repair action:

```
// pyblish.pyblish.plugin.Action : Finding failed instances..
// pyblish.pyblish.plugin.Action : Attempting repair for instance: rayman_rigMain_01_ ...
// Error: pyblish.plugin : Traceback (most recent call last):
//   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
//     runner(*args)
//   File "D:\REPO\OpenPype\openpype\pipeline\publish\publish_plugins.py", line 243, in process
//     plugin.repair(instance)
//   File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_frame_range.py", line 139, in repair
//     if cmds.attributeQuery("handleStart", node=node, exists=True):
// TypeError: No object matches name: rayman_rigMain_01_
// Traceback (most recent call last):
//   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
//     runner(*args)
//   File "D:\REPO\OpenPype\openpype\pipeline\publish\publish_plugins.py", line 243, in process
//     plugin.repair(instance)
//   File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\publish\validate_frame_range.py", line 139, in repair
//     if cmds.attributeQuery("handleStart", node=node, exists=True):
// TypeError: No object matches name: rayman_rigMain_01_
```

### Expected Behavior:

If ```frame range``` being different from DB entries for current ```asset``` Validator's ```Repair``` action should fix those so the ```frame ranges``` matches DB.

### Version

3.16.4

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Create ```Animation``` or ```Pointcache``` or any other instance with ```frame range``` attribs
2. Change ```frame range``` so they differ from database entry
3. Try to ```Publish```
4. Use ```Repair``` action to fix ```frame ranges```
5. Publish should happen without erroring out

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-6718](https://app.clickup.com/t/861najumy)]

**Comment by BigRoy** [comment]
This particular [line](https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/validate_frame_range.py#L128) I think should refer to `instance.data["instance_node"]` instead.
```python
        node = instance.data["instance_node"]
```

If so, [this](https://github.com/ynput/OpenPype/blob/67cd2ff6506e2065c64c88f6848b84a465d9305b/openpype/hosts/maya/plugins/publish/validate_model_content.py#L34) might also be wrong.

**Comment by shobhit9957** [comment]
I would like to contribute to this. Please help me out..

**Comment by shobhit9957** [comment]
Thanks @BigRoy , will follow the steps you've provided and update you with the feedbacks.  Thanks!

**Comment by BigRoy** [comment]
@shobhit9957 Any luck with this?

**Comment by shobhit9957** [comment]
Nothing, getting confused. I'm just a beginner to this open-source community...so it takes time. Can you please provide me some more detailed information...because that will provide me some more context. Thanks you, sorry for the late...

**Comment by BigRoy** [comment]
@shobhit9957 It's hard to get into detail to get you on track the right way. To help you out it's important that you clarify where you get stuck.

1. What did you try?
2. Where did you get confused? What went differently than you expected?

**Comment by shobhit9957** [comment]
Actually, I got confused by seeing that big issue description, so I didn't even try my hands on. but I'll go through it throughly and try it....let's see what my beginner friendly skills can do. sorry @BigRoy you maybe expecting me to be a "G" here, but I'm actually a noob. but I'll give it a try...sorry.
