### ISSUE TITLE
Houdini: Bgeo extractor crashes when rendering current frame

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

`instance.data` will not have `"frameStart"` and `"frameEnd"` 
![image](https://github.com/ynput/OpenPype/assets/20871534/024c6a9a-807a-4843-b09a-af74696c8e98)

### Expected Behavior:

A quick fix to modify extractor as such
```python
# A single frame may also be rendered without start/end frame.
if "frameStart" in instance.data and "frameEnd" in instance.data:
    representation["frameStart"] = instance.data["frameStart"]
    representation["frameEnd"] = instance.data["frameEnd"]
```

A more in depth fix to 
- add a validator that add or remove `$F4` in `sopoutput` according to the value of `trange`

### Version

3.16.4

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Create a bgeo instance
2. Set  `Valid Frame Range` to `Render Current Frame` 
![image](https://github.com/ynput/OpenPype/assets/20871534/9b78cc55-687d-4e46-a8d9-dec9471c8a3e)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-6724](https://app.clickup.com/t/861najun9)]

**Comment by BigRoy** [comment]
I've mentioned this elsewhere - but from a pipeline perspective the "Render Current Frame" isn't a very informative and safe option. Opening the workfile makes it quite unclear what was originally the intended frame be published?
Not saying it's unimaginable to support it - but even if we would from a safety perspective I'd still recommend refraining from using it.

**Comment by mustafa-zarkash** [comment]
> I'd still recommend refraining from using it.
So, it's better to add a validator that make sure trange != 0 instead of adding support for single frame at the moment?

**Comment by BigRoy** [comment]
> So, it's better to add a validator that makes sure trange != 0 instead of adding support for single frame at the moment?

Hard to say what the community wants. For our production use cases I'd say not support `trange == 0` would be perfectly fine. A validator could solve that yes, which could offer a repair which can set the toggle to "Render frame range" but with start and end frame on the current frame to help the artist.

**Comment by mustafa-zarkash** [comment]
This comment relates to this issue. 
https://github.com/ynput/OpenPype/pull/5529#issuecomment-1697480805
