### ISSUE TITLE
Bug: QWidget error Resolve 18 (Failed to create)

### ISSUE THREAD

**Issue by aramadan0096** [ynput/OpenPype#5515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

I can't create shots in Resolve 18.1

### Expected Behavior:

Setting naming convention to match kitsu entities using OpenPype create, before publishing them as shots assets.

### Version

3.16.3

### What platform you are running OpenPype on?

MacOS

### Steps To Reproduce:

1. followed instructions here:
https://github.com/ynput/OpenPype/tree/develop/openpype/hosts/resolve
+ installing PyQt 5 + install OpenTimelineIO using pip install

2. select shots then Resolve/EditTab/Menu/Workspace/Scripts/Comp/OpenPype_Menu
3. Create then create from instance creator 
4. I get this error:
```
Failed to create Subset: "clipMain" Family: "clip" in Asset: "Sc002_Sh0010"

Error: 'QWidget' object has no attribute 'addRow'

Traceback (most recent call last):
  File "/Applications/OpenPype 3.16.3.app/Contents/MacOS/openpype/tools/creator/window.py", line 431, in _on_create
    legacy_create(
  File "/Applications/OpenPype 3.16.3.app/Contents/MacOS/openpype/pipeline/create/legacy_create.py", line 202, in legacy_create
    instance = plugin.process()
  File "/Applications/OpenPype 3.16.3.app/Contents/MacOS/openpype/hosts/resolve/plugins/create/create_shot_clip.py", line 223, in process
    widget = self.widget(self.gui_name, self.gui_info, self.gui_inputs)
  File "/Applications/OpenPype 3.16.3.app/Contents/MacOS/openpype/hosts/resolve/api/plugin.py", line 64, in __init__
    self.items = self.populate_widgets(ui_inputs)
  File "/Applications/OpenPype 3.16.3.app/Contents/MacOS/openpype/hosts/resolve/api/plugin.py", line 248, in populate_widgets
    data[k]["value"] = self.populate_widgets(
  File "/Applications/OpenPype 3.16.3.app/Contents/MacOS/openpype/hosts/resolve/api/plugin.py", line 252, in populate_widgets
    data[k]["value"] = self.create_row(
  File "/Applications/OpenPype 3.16.3.app/Contents/MacOS/openpype/hosts/resolve/api/plugin.py", line 166, in create_row
    layout.addRow(label, item)
AttributeError: 'QWidget' object has no attribute 'addRow'
```

![Untitled](https://github.com/ynput/OpenPype/assets/57462754/843507fa-022a-44e1-829b-23b002e3e285)

 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Resolve console output:

>>> [ openpype.hosts.resolve installed ] 
>>> [ Registering DaVinci Resovle plug-ins.. ] 
>>> [ Assigning resolve module to `pype.hosts.resolve.api.bmdvr`: Resolve (0x0x11831e340) [App: 'Resolve' on 127.0.0.1, UUID: d4adaf10-3293-48d3-afc4-dbab144a44a3] ] 
>>> [ Assigning resolve module to `pype.hosts.resolve.api.bmdvf`: FusionUI (0x0x230ed7040) [App: 'Resolve' on 127.0.0.1, UUID: d4adaf10-3293-48d3-afc4-dbab144a44a3] ] 
Clicked Create
Using existing QApplication..
Registered font families: Noto Sans, Noto Sans, Noto Sans, Noto Sans, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono, Noto Sans Mono
Running <create_shot_clip.CreateShotClip object at 0x7f7b3322beb0> with maintained selection
```
```


### Additional context:

_No response_

**Comment by aramadan0096** [comment]
[](url)after a some reviewing I decided to replace "layout" parameter with a "layout" variable to be:
```
        # add to layout
        QFormLayout().addRow(label, item)
```        
instead of:
```
        # add to layout
        layout.addRow(label, item)
```

Then I tied to create and finaly I got no errors but the Shot Creator window got corrupted
![IMG_20230830_214704-01](https://github.com/ynput/OpenPype/assets/57462754/65865ff2-7ead-42b9-a064-cfc36f8df0d3)

**Comment by BigRoy** [comment]
This has been resolved on discord. It's a bit hard to pinpoint what the exact issue was but it seemed the codebase of @aramadan0096 did an import from `PyQt5` instead of `qtpy` or `QtPy` and thus had code changes that were never present in OpenPype for the relevant files. However, debugging on discord also showed that `PyQt5` was used in resolve.

After removing `PyQt5` and installing `PySide2` **and** reinstalling OpenPype (to remove @aramadan0096's local changes) the UI worked fine.

Whether the UI breaks in `PyQt5` or whether the issue was just local changes by @aramadan0096 is still unclear. But since apparently it's solved with `PySide2` + a fresh install I'll close this issue.
