### ISSUE TITLE
Houdini: Reset FPS

### ISSUE THREAD

**Issue by mustafa-zarkash** [ynput/OpenPype#5516]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

_Similar to Maya_, Make `Set Frame Range` resets FPS 

![image](https://github.com/ynput/OpenPype/assets/20871534/561d2779-40f8-40c5-ada1-22946e32b2e7)

### How would you imagine the implementation of the feature?

add `hou.setFps` to this function:

https://github.com/ynput/OpenPype/blob/437f483bc48c8f8cdb38b181d9a1c6ec305388aa/openpype/hosts/houdini/api/lib.py#L474

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by BigRoy** [comment]
Sounds good to me. Just make sure to also update [these lines of code](https://github.com/ynput/OpenPype/blob/437f483bc48c8f8cdb38b181d9a1c6ec305388aa/openpype/hosts/houdini/api/pipeline.py#L388-L393) to avoid it doing so twice.

**Comment by mustafa-zarkash** [comment]
I've found out that there's a `before_save` callback that validates FPS! 
So, we may not need `reset_framerange()` to deal with that! 
What do you think ? 

https://github.com/ynput/OpenPype/blob/fd64e261df0371b16395aa5238fee1eb6f0fd705/openpype/hosts/houdini/api/pipeline.py#L294-L295
