### ISSUE TITLE
Bug: Extract Look in Maya with rstexbin doesn't set correct colorspace when OCIO managed

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#5640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When Maya is set with `OCIO` config, converting textures to `rstexbin` format fails, because the extractor fails. It needs to set source colorspace via `-cs` argument. Output is slightly confusing:

```
Failed to get  -> Utility - Linear - Rec.709 processor from OpenColorIO config
        ocio exception: ColorSpaceTransform: empty source color space name.
```
because `Utility - Linear - Rec.709` is defined in the config.

This prevents publishing looks with rstexbin conversion enabled in OCIO managed Maya.

### Expected Behavior:

`redshiftTextureProcessor` should get correct source colorspace. Publishing should work even with `rstexbin` enabled.

### Version

3.17.0

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Set OCIO to ACES config
2. Try to publish look in maya with textures, and `rstexbin` enabled.
you can test it manually in command line:
```powershell
& .\redshiftTextureProcessor.exe C:\Projects\xxxxx_boo_textureMain.BaseColor_v000.png
```
vs.
```powershell
& .\redshiftTextureProcessor.exe C:\Projects\xxxxx_boo_textureMain.BaseColor_v000.png -cs "Utility - Linear - Rec.709"
```

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
.\redshiftTextureProcessor.exe C:\Projects\xxxxx_boo_textureMain.BaseColor_v000.png
Converting from source images


Found and loaded OCIO config file: "C:\Users\annat\Documents\Projects\OpenPype\sources\ayon-desktop\vendor\bin\ocioconfig\OpenColorIOConfigs\aces_1.2\config.ocio"
Processing texture: C:\Projects\xxxxx_boo_textureMain.BaseColor_v000.png

Failed to get  -> Utility - Linear - Rec.709 processor from OpenColorIO config
        ocio exception: ColorSpaceTransform: empty source color space name.
Failed to get  -> Utility - Linear - Rec.709 processor from OpenColorIO config
        ocio exception: ColorSpaceTransform: empty source color space name.
Finished processing 1 textures
```

[cuID:[OP-6940](https://app.clickup.com/t/86bw112x1)]

**Comment by antirotor** [comment]
Maybe I am wrong but since the `-cs` argument of `redshiftTextureProcessor` needs the transformation from something to scene linear, this needs to be handled by file rules more than by some kind of mapping. We might need #5273 for this.

**Comment by BigRoy** [comment]
> `dshiftTextureProcessor` needs the transformation from something to scene linear, this needs to be handled by file rules more than by some kind of mapping. We might need #5273 for thi

I'd actually just match whatever your Maya color management is set to just so that whatever the lookdev artist is seeing is also what will be baked in. We've done the same for [TX generation color spave conversions](https://github.com/ynput/OpenPype/blob/d595d12b781a8839ea99b7a531f87bad3202c398/openpype/hosts/maya/plugins/publish/extract_look.py#L309-L320).

Basically, convert the colorspace that is set on the file node to the rendering colorspace of your scene.

As such, convert it to: `openpype.hosts.maya.api.lib.get_color_management_preferences()["rendering_space"]` like the code linked above does?
