### ISSUE TITLE
Bug: Publish Job in Deadline Missing During Job Mantra Publishing

### ISSUE THREAD

**Issue by spmhickstein** [ynput/OpenPype#5707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When attempting to publish a Job Mantra, the Publisher fails to create a Publish Job in Deadline. The absence of a Publish Job in Deadline prevents the successful publishing of the rendered Job Mantra.

### Expected Behavior:

Upon initiating the process of publishing a Job Mantra, two jobs should be created on Deadline: the Mantra Job, and subsequently, the Ayon Publish Job. The Ayon Publish Job is expected to be generated after the Mantra Job rendering has concluded.

### Version

3.17.2-nightly.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Initiate the process of publishing a Job Mantra.
2. Proceed through the steps necessary for publishing.
3. Observe that the Publish Job in Deadline is missing.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
As reported on Discord by @spmhickstein [here](https://discord.com/channels/517362899170230292/1159493303373406270/1159503645507854387) a _hotfix_ seemed to be to add:
```python
instance.data["toBeRenderedOn"] = "deadline"
```
In: `submit_houdini_render_deadline.py`

**Comment by MustafaJafar** [comment]
Could you share us your deadline log ? maybe we can find something in it ? 

--- 

I've here 
- `3.17.2-nightly.3`
- houdini 0.1.4 
- deadline 0.1.1

![image](https://github.com/ynput/OpenPype/assets/20871534/380b9c31-1f3c-46a5-a095-7d8275e64924)

**Comment by BigRoy** [comment]
> Could you share us your deadline log ? maybe we can find something in it ?

I suspect the issue isn't Deadline related because the Job itself gets submitted to Deadline even before Deadline starts being involved. The log we'd need would the publish report log (preferably "Saved to disk" from the Publisher UI) from the Houdini session.
