### ISSUE TITLE
Enhancement: Make Houdini Creator deduce family/families using creator identifier

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5712]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Deduce families from creator identifier in Houdini. 

Quoting BigRoy comment: 

> Having this always defined by the creator and not saved into the node will also allow us to maintain the code easier since we don't need to ensure whatever data is on the node matches what the Creator has as family (or families; which has been an occurrence with bgeo + alembic in Houdini; but also with USD families in Maya which I solved exactly like that; the Creator always defines the families and is not embedded onto the container, see this [PR](https://github.com/ynput/OpenPype/pull/5490)

### How would you imagine the implementation of the feature?
Quoting BigRoy comment: 

> This should happen on create AND on collect_instances, since that's when the Creator creates the instances for the CreateContext. Additionally this data should not be stored on the instance node in the scene (it should not be stored in parms on the node, it should not be serialized because the Creator defines the families).

One could argue it's actually transient_data but the publish system needs it in instance.data["families"] due to how pyblish works.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[OP-7105](https://app.clickup.com/t/86bw4gg46)]

**Comment by BigRoy** [comment]
I believe it's still relevant for pointcache specifically in AYON - but I'd say... we're looking to refactor bigger than just this one. It's fine to put it on the backlog and move to ayon-houdini - but at the same time it's not something that I'd "fix" in isolation - rather focus on the overall publishing redesign of AYON x Houdini

**Comment by MustafaJafar** [comment]
Should we close it then  ?

**Comment by BigRoy** [comment]
Burn it with fire until it becomes an issue again - if we don't end up solving it magically via our other goals. 🔥
