### ISSUE TITLE
Bug: Local Render Publish Support in Houdini

### ISSUE THREAD

**Issue by moonyuet** [ynput/OpenPype#5716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When the farm instance disabled in Houdini render ROPs, it doesn't get published after local rendering. 
See here: https://discord.com/channels/517362899170230292/1159640714649542696/1160121840354734080

### Expected Behavior:

It can be locally published to the published folder after the farm, similar to Nuke and FUsion
We should support local rendering alongside farm rendering, users can choose their preferences to use whether local or farm for rendering.

### Version

3.17.2-nightly.3

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Create any Render Instance in Houdini and disables farm instance
2. Publish

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-7093](https://app.clickup.com/t/86bw4gg41)]

**Comment by moonyuet** [comment]
@fabiaserra for some reason I can't add you as assignee. It would be great you can also join the discussion too.

**Comment by BigRoy** [comment]
> When the farm instance disabled in Houdini render ROPs, the render doesn't get published after deadline submission

I think this sentence is wrong? :) If farm is disabled then it doesn't submit to Deadline to begin with, right?

I personally would just expect - if submitting to the farm can be disabled on the instance - that the behavior is the [same as Nuke](https://github.com/pypeclub/OpenPype/blob/a75e5d8db6aad7c0462af8f1637080f8c619ca0e/openpype/hosts/nuke/api/plugin.py#L328-L335)/Fusion where one just has a render toggle between "Local rendering" or "Render on the farm" - but no matter which option I'd pick I'd at least expect my files to get published. If local render publishes don't get published then they are basically the same as clicking "Save to disk" on the ROP node without a pipeline, right?

Also, if we're tweaking the option I'd also expect an option like with Fusion/Nuke to publish existing frames maybe?

**Comment by moonyuet** [comment]
> > When the farm instance disabled in Houdini render ROPs, the render doesn't get published after deadline submission
> 
> I think this sentence is wrong? :) If farm is disabled then it doesn't submit to Deadline to begin with, right? I assume you meant "doesn't get published after local rendering"?
> 
It is indeed not elaborated well, I edited the changelog of the issue for better description of the issue.

> I personally would just expect - if submitting to the farm can be disabled on the instance - that the behavior is the [same as Nuke](https://github.com/pypeclub/OpenPype/blob/a75e5d8db6aad7c0462af8f1637080f8c619ca0e/openpype/hosts/nuke/api/plugin.py#L328-L335)/Fusion where one just has a render toggle between "Local rendering" or "Render on the farm" - but no matter which option I'd pick I'd at least expect my files to get published. If local render publishes don't get published then they are basically the same as clicking "Save to disk" on the ROP node without a pipeline, right?
> 
> Also, if we're tweaking the option I'd also expect an option like with Fusion/Nuke to publish existing frames maybe?

We can defnitely expect the options for existing frames in this case. 
If we take reference from Nuke/Fusion, this is probably what we expect to add technically for local rendering:
1. A toggled button/option to allow users to choose "local" or "farm" for rendering
2. Extractor for local rendering(some image sequences) and Extractor which renders image sequences for burnin. (I am thinking if we can just use one extractor for Houdini's case)
3. If we add burnin for the rendered image sequences, which means the review family needs to be included as part of the family.

**Comment by MustafaJafar** [comment]
is this issue the same as reported here ? 
https://github.com/ynput/OpenPype/issues/5482

**Comment by BigRoy** [comment]
> is this issue the same as reported here ? , if yes, please confirm so that I can close the other issue. #5482

Yes, sounds very similar.

**Comment by BigRoy** [comment]
That's also something I assumed, the farm setting would be a Creator attribute definition `get_instance_attr_defs()` on the Creator. - so it's a publish attribute first.

**Comment by BigRoy** [comment]
Pretty sure this is solved in AYON - right @MustafaJafar. Time to close?

**Comment by MustafaJafar** [comment]
Yes, Pretty sure this is solved in AYON
Let's burn it 🔥
