### ISSUE TITLE
Bug: Houdini Shelves Manager is not working properly in Ayon

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Houdini Shelves Manager Settings in Ayon are different than in OpenPype settings

<table>
<tr><td>OpenPype</td><td>Ayon</td></tr>
<tr><td><img src=https://github.com/ynput/OpenPype/assets/20871534/e35d8ab1-a943-4ba3-96c3-aed2d2839541></td><td><img width="600" src=https://github.com/ynput/OpenPype/assets/20871534/8f96efd2-03ba-41a6-a263-51d64c98c799></td>
</tr>
</table>

### Expected Behavior:

Settings in both should be the same so that we don't have to rewrite the tool for ayon

### Version

3.17.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. try to create a houdini shelf in Ayon

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by MustafaJafar** [comment]
@moonyuet  @BigRoy 
I think it's good to have a `MultiplatformPath` for shelf set paths and script paths 
but do we need that for icon path ??

**Comment by BigRoy** [comment]
> I think it's good to have a MultiplatformPath for shelf set paths and script paths
> but do we need that for icon path ??

I suppose if we do one, that we also allow it for the other, yes.

**Comment by MustafaJafar** [comment]
This Issue should be fixed by this PR https://github.com/ynput/OpenPype/pull/5748 
as it aligns openpype and ayon settings so that houdini addon become compatible 

if script path needs to be a multiplatform path then we should create an issue so that we add that enhancement for both OP and ayon

![image](https://github.com/ynput/OpenPype/assets/20871534/b5831877-1443-4d5b-abb5-7c18db71b905)
