### ISSUE TITLE
Bug: Houdini composite ROP is created with wrong frame start and end

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When creating new composite ROP node, a wring frame range is used. 

![image](https://github.com/ynput/OpenPype/assets/20871534/dd858d16-53d5-43ab-8783-4fadec414e1b)

### Expected Behavior:

it should at least be created with the same frame range is in the current houdini session 

it'll be a quick fix in the creator plugin 

```python
frame_range = hou.playbar.frameRange()
parms = {
            "trange": 1,
            "copoutput": filepath,
            # Unlike many other ROP nodes the composite node does not default
            # to expression of $FSTART and $FEND so we preserve that behavior
            # but do set the range to the frame range of the playbar
            "f1": frame_range[0],
             "f2": frame_range[1]
        }
```

### Version

3.17.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

create a composite publish

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-7222](https://app.clickup.com/t/86bw9bv51)]

**Comment by BigRoy** [comment]
Thanks for the clear issue reports!

Just wanted to remark that if some of these require simple fixes and are easy to explain in the PR without needing discussion _and_ you now how to fix them then you're just as well off only creating the PR itself if that saves you time. Not sure how everyone else sees that but I'd be fine with that.

**Comment by MustafaJafar** [comment]
I agree with you! 
but I can't do so now because I'm in the middle of something and can't exit it to make the dedicated PR. 
I'm currently [updating Houdini docs](https://github.com/ynput/ayon-documentation/pull/83) and making quick tests to check if things working fine.
