### ISSUE TITLE
Enhancement: Houdini publish existing caches/frames

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5767]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Problem description: 
Houdini simulations need many iterations so artists can keep adding tweaks and once they are comfortable they will consider publishing. 
Also, simulations are CPU intensive so most of times it will be a problem to re-render or re-cache to just publish (register data to AYON/OpenPype DB)
However, publishing is not just about registering data to the DB, it's also about running validations to ensure these data imply to studio's specifications. 

one solution that we came up with in community to have a toggle on the ROP node that skips the render action so it will just validate these data before publishing. 

in this screen shot, alembic pointcache rop is reading a file read sop node. 
![image](https://github.com/ynput/OpenPype/assets/20871534/615d63ea-a439-447f-9e53-c8d25ec6f9f1)

### How would you imagine the implementation of the feature?

1. add `use_existing` checkbox in creator plugin

2. use it in extractors so, it skips rendering
```python
if not instance.data["use_existing"]:
  render_rop(ropnode)
```

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Describe alternatives you've considered:

another solution would be to have a universal publish node that's only purpose to publish.

### Additional context:

Feel free to add your ideas and suggestions. 

[cuID:[OP-7229](https://app.clickup.com/t/86bw9bv50)]

**Comment by BigRoy** [comment]
Instead of a **Use existing** checkbox I think we're better of making an **ENUM** attribute similar to Fusion and Nuke does for renders. There you have the option [defined here](https://github.com/ynput/OpenPype/blob/ce3e9a52401fdd85a6574b6fafc0d23351e69135/openpype/hosts/nuke/api/plugin.py#L324-L331) to:

- Use Existing Frames
- Local Machine Render
- Farm Rendering
- Use Existing Frames - farm

Having an enum makes it easier to understand what's going on and will also make sure that "Existing frames" + "Local or farm" etc can be tackled in unison.

**Comment by krishna8008** [comment]
Need these options same for Review family as well please, we can take advantage of rendering opengl in deadline machines, and publish existing frames, currently there is a limitation of publishing locally, Huge size caches are eating so much of time on this limitation.

**Comment by MustafaJafar** [comment]
I got it! Totally make sense. 

Here's a screenshot for reference
![image](https://github.com/ynput/OpenPype/assets/20871534/c11ade3a-5450-4fad-9ca7-37c697dc1a4d)

**Comment by MustafaJafar** [comment]
re-created on ayon https://github.com/ynput/ayon-houdini/issues/19
