### ISSUE TITLE
Nested Template workflow

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#5772]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Currently, the template workflow supports nesting, but setting it up can be quite complicated. This is because there are placeholders pointing to a published backdrop product which is containing other placeholders that need to be resolved. Configuring it is not easy, and we need to find a simpler solution.

### How would you imagine the implementation of the feature?

Simplification can be achieved by creating group nodes within the template and using specific placeholders that reference these groups. This means that the groups become integrated into the template, and once the template is resolved and the groups are utilized, they will be removed from the script.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Describe alternatives you've considered:

I can't think of a better alternative.

[cuID:[OP-7130](https://app.clickup.com/t/86bw5d4w3)]

**Comment by tokejepsen** [comment]
Think this is similar to my suggestion [here](https://community.ynput.io/t/maya-templates-improvements/174/9) about tagging loaded containers as placeholders so we can work with content in the templates rather than theoretical content.

**Comment by jakubjezek001** [comment]
closing in favour of https://github.com/ynput/ayon-nuke/issues/5
