### ISSUE TITLE
Bug: Houdini CreateHDA still contains legacy code

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/OpenPype#5818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Houdini create plugin `CreateHDA ` is still using `self.data` which is available only in `LegacyCreator` https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/houdini/plugins/create/create_hda.py#L25

### Expected Behavior:

It should not use `self.data`, so the method should expect asset name/id as argument.

### Version

3.17.4-nightly.1

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Replicate a code bug?

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-7224](https://app.clickup.com/t/86bw9bv56)]

**Comment by BigRoy** [comment]
Seems fixed in OpenPype already - but definitely fixed in AYON.
