### ISSUE TITLE
Maya: Look allow referenced materials publish

### ISSUE THREAD

**Issue by mkolar** [ynput/OpenPype#59]
<p>We should allow publishing a look that has referenced materials loaded from a material library (ground, water, fire, etc) </p>

<p>This material wouldn't be in the lookdev scene originally but in matlib.</p>
<i>[PYPE-375] created by admin</i>

[cuID:[OP-1217](https://app.clickup.com/t/yjy05a)]

**Comment by BigRoy** [comment]
The look extractor would "import" the reference in the publish already and thus does allow using a lookdev from matlib in a lookdev. However, it'd transfer and copy the (potentially processed files, like e.g. through `maketx`) into the publish folder. I think that'll always be needed to correctly support sitesync (if e.g. the site only that this project available, etc.)

As such, I believe it should already be possible to use looks from the matlib - although likely at first publish it _will_ report invalid ids which I think you can regenerate, if not.. then _that's_ the issue that'd need to be solved.

What's the particular tweak you feel need to be done to make this more appropriate for using materials from matlib?

**Comment by mkolar** [comment]
You're right this is technically already possible and didn't get any interest since it was created ages ago. Closing.
