### ISSUE TITLE
Bug: Error while publishing from Blender

### ISSUE THREAD

**Issue by alainxi** [ynput/OpenPype#6049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Everytime I publish from Blender, I get an error (see the log output below), that is only displayed in Blender's output console 
(Window-->Toggle System Console).

### Expected Behavior:

The publish should not raise an error, in that case.

### Version

3.17.7-nightly.6

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Using the Launcher, start Blender.
Create a mesh, save the scene.
Select the mesh, and use the menu Ayon-->Create (as a model).
Publish.
The Publisher displays no error, but Blender's output window does (see the logs below).

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
>>> [ *** Discovered 2 abstract plugins
- AutoCreator
- BaseCreator ]
>>> [  Auto-creating workfile instance...  ]
!!! ERR: 2023-12-13 11:41:26,446 >>> { CreateWorkfile }: [  Unable to update instance <CreatedInstance OrderedDict([('id', 'pyblish.avalon.instance'), ('family', 'workfile'), ('subset', 'workfileModeling'), ('active', True), ('creator_identifier', 'io.openpype.creators.blender.workfile'), ('variant', 'modeling'), ('creator_attributes', <openpype.pipeline.create.context.CreatorAttributeValues object at 0x00000169C6EE66B0>), ('publish_attributes', <openpype.pipeline.create.context.PublishAttributes object at 0x00000169C6EE5B70>), ('task', 'modeling'), ('folderPath', '/PROD/CREA/ASSETS_3D/GRASS'), ('instance_id', '64cdee1b-7f48-4737-b157-ec4da5aa1641')]) (workfile[io.openpype.creators.blender.workfile])> OrderedDict([('id', 'pyblish.avalon.instance'), ('family', 'workfile'), ('subset', 'workfileModeling'), ('active', True), ('creator_identifier', 'io.openpype.creators.blender.workfile'), ('variant', 'modeling'), ('creator_attributes', <openpype.pipeline.create.context.CreatorAttributeValues object at 0x00000169C6EE66B0>), ('publish_attributes', <openpype.pipeline.create.context.PublishAttributes object at 0x00000169C6EE5B70>), ('task', 'modeling'), ('folderPath', '/PROD/CREA/ASSETS_3D/GRASS'), ('instance_id', '64cdee1b-7f48-4737-b157-ec4da5aa1641')]) without instance node.  ]
```

### Additional context:

I tried to publish the Model and the Workfile at once, or only the Model, or only the Workfile (and reseted between each tries), with always the same results.

[cuID:[OP-7600](https://app.clickup.com/t/86bwtdyu2)]

**Comment by BigRoy** [comment]
Adding as a reference:

- Discussion starting [here](https://discord.com/channels/517362899170230292/890894521817260052/1184446129954361364) and [continuing here](https://discord.com/channels/517362899170230292/517382145552154634/1184452349813587988)
- This PR should be solving it [somewhat](https://github.com/ynput/OpenPype/pull/6048)

**Comment by LiborBatek** [comment]
This isnt an issue anymore, didnt spotted in the ```latest develop``` so I guess could be closed ? @iLLiCiTiT @antirotor

**Comment by alainxi** [comment]
I just checked today, using openpype_3.18.3-nightly.1 (develop from january 9th), and got exactly the same bug :


Initialising WM_OT_avalon_creator...
Using existing QApplication..
>>> [ *** Discovered 2 abstract plugins
- AutoCreator
- BaseCreator ]
>>> [  Auto-creating workfile instance...  ]
!!! ERR: 2024-01-15 09:43:40,712 >>> { CreateWorkfile }: [  Unable to update instance <CreatedInstance OrderedDict([('id', 'pyblish.avalon.instance'), ('family', 'workfile'), ('subset', 'workfileModeling'), ('active', True), ('creator_identifier', 'io.openpype.creators.blender.workfile'), ('variant', 'modeling'), ('creator_attributes', <openpype.pipeline.create.context.CreatorAttributeValues object at 0x000001E52F8458D0>), ('publish_attributes', <openpype.pipeline.create.context.PublishAttributes object at 0x000001E52F844EB0>), ('task', 'modeling'), ('folderPath', '/PROD/CREA/ASSETS_3D/WHEEL'), ('instance_id', '32ab60c6-8ca2-4875-80c2-82afa038a5f6')]) (workfile[io.openpype.creators.blender.workfile])> OrderedDict([('id', 'pyblish.avalon.instance'), ('family', 'workfile'), ('subset', 'workfileModeling'), ('active', True), ('creator_identifier', 'io.openpype.creators.blender.workfile'), ('variant', 'modeling'), ('creator_attributes', <openpype.pipeline.create.context.CreatorAttributeValues object at 0x000001E52F8458D0>), ('publish_attributes', <openpype.pipeline.create.context.PublishAttributes object at 0x000001E52F844EB0>), ('task', 'modeling'), ('folderPath', '/PROD/CREA/ASSETS_3D/WHEEL'), ('instance_id', '32ab60c6-8ca2-4875-80c2-82afa038a5f6')]) without instance node.  ]

**Comment by iLLiCiTiT** [comment]
PR https://github.com/ynput/OpenPype/pull/6048 was merged on Thursday 11.1.2024 /

**Comment by alainxi** [comment]
I cannot test on the latest develop (unrelated problem), but I tested on openpype_3.18.3-nightly.1 , on which I replaced the openpype\hosts\blender\plugins\create\create_workfile.py file  by the one modified by PR #6048.
https://github.com/ynput/OpenPype/pull/6048/files

I works all right now
![success](https://github.com/ynput/OpenPype/assets/85064149/7b0c2fd0-dea3-4b1d-9e7f-917fb87ea34a)
.

**Comment by LiborBatek** [comment]
Been resolved already so working without any issues so Closing...
