### ISSUE TITLE
Bug: Houdini Publish error when publishing Bgeo Bgeo.Sc (single Frame / Frame Range)

### ISSUE THREAD

**Issue by Lyon-Rosenblatt-Ynput** [ynput/OpenPype#6178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

when Publishing Bgeo sequence from Houdini the Integrate Hero Version errors do to missing Values. 

File "/home/workh/Ynput/dev/OpenPype/openpype/plugins/publish/integrate_hero_version.py", line 363, in integrate_instance
    head, tail = _template_filled.split(frame_splitter)
 ValueError: not enough values to unpack (expected 2, got 1)
 
When Publishing Bgeo in Single Frame mode. publish deletes the .bgeo / bgeo.sc extensions from the files that are stored in the Vxxx and hero folders. 
The Work file Export is fine tho. 

 

### Expected Behavior:

Expected behavior would be that the Export copies/published the right files into the Vxxx and Hero founders 
i would also expect that hero integration would get the right Data in order to process the integration on sequence files. 

### Version

3.18.5

### What platform you are running OpenPype on?

Windows, Linux / RedHat

### Steps To Reproduce:

For Sequence 
1. Open Houdini Create some points 
2. Create a Bgeo export from the Create menu 
3. Set the Export to single Frame 
4. Look into the error logs and go to Integrate Hero Version 

For Single Frame Export 
3. set frame range ENUM (Valid Frame Range) to (Current)
4. Publish 
5. Look into Hero/Vxxx foulder // the file extension will be . instead of .bgeo.sc / .bgeo

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
------------------------------------- Frame Range --------------------------------------

File "/home/workh/Ynput/dev/OpenPype/openpype/plugins/publish/integrate_hero_version.py", line 363, in integrate_instance
    head, tail = _template_filled.split(frame_splitter)
 ValueError: not enough values to unpack (expected 2, got 1)


------------------------------------- Single --------------------------------------
DEBUG: Integrating source files to destination ...
DEBUG: Checking file ... /home/workh/Documents/AyonUsd/Usd_Base/Assets/sim_r42/work/test_sim_r42/pyblish/pointcacheGustaf.1126.bgeo.sc -> /home/workh/Documents/AyonUsd/Usd_Base/Assets/sim_r42/publish/pointcache/pointcacheGustaf/v005/UB_sim_r42_pointcacheGustaf_v005.
DEBUG: Copying file ... /home/workh/Documents/AyonUsd/Usd_Base/Assets/sim_r42/work/test_sim_r42/pyblish/pointcacheGustaf.1126.bgeo.sc -> /home/workh/Documents/AyonUsd/Usd_Base/Assets/sim_r42/publish/pointcache/pointcacheGustaf/v005/UB_sim_r42_pointcacheGustaf_v005.
```

[cuID:[OP-8055](https://app.clickup.com/t/86bx8n3jt)]

**Comment by MustafaJafar** [comment]
I believe is no longer happening in ayon.
Therefore, closing this issue.
