### ISSUE TITLE
Bug: Nuke template placeholder knobs duplicity after update

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/OpenPype#6209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Once the Updating placeholder tool is used on already created placeholders and plugin is changed then placeholder node knobs are duplicated. More details lower in additional context.

### Expected Behavior:

Knobs should not be duplicated but only updated

### Version

3.18.7-nightly.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. open empty workfile under Ayon addon with some task context
2. from Ayon menu find Template builder and Create placeholder to some configuration (LoadClip)
3. Then select the created node of placeholder and open properties bin so you can see the knob duplicty
4. Open Update placeholder form Ayon menu / template builder submenu
5. change plugin selection to `Load image`
6. See that knobs were duplicated

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Additional context:

![mutliselectiontest](https://github.com/ynput/OpenPype/assets/40640033/39b0fca7-42e5-4790-85d9-b83304287707)

[cuID:[OP-8169](https://app.clickup.com/t/86bxemf73)]

**Comment by BigRoy** [comment]
Not sure why this group of people was assigned to this issue. What would you like us to do with this @mkolar ? (You assigned this group to this issue and some others - the question is about all those assignments really).


For this particular issue I believe a PR is set up to Ayon core here https://github.com/ynput/ayon-core/pull/187 which seems to describe solving this particular issue.
