### ISSUE TITLE
Bug: Action failed window doesn't show up

### ISSUE THREAD

**Issue by JoseCaraballoOS** [ynput/OpenPype#6234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

PR #6179 introduced a new feature where a window will display the error and stack trace of a failed action. 

This feature is not working because the wrong arguments were passed to the function. Here you can see what is displayed in the Maya script editor console. 
![ERROR-ACTION](https://github.com/ynput/OpenPype/assets/160849460/62385f7f-9d0a-4a6f-b0d6-176fcd16decc)

### Expected Behavior:

Expected behavior is for a window to appear and display the error like this: 
![ACTION-WORKING](https://github.com/ynput/OpenPype/assets/160849460/6ab63c6e-f2d8-45b6-ac37-2c55f36a8a01)

### Version

3.18.8-nightly.1

### What platform you are running OpenPype on?

Linux / Centos

### Steps To Reproduce:

Make an action fail on purpose and run it. "Action Failed" window won't show up. 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by JoseCaraballoOS** [comment]
I'm not sure if a PR is needed in AYON.

**Comment by tokejepsen** [comment]
> I'm not sure if a PR is needed in AYON.

Sure does :) https://github.com/ynput/ayon-core/pull/120

**Comment by JoseCaraballoOS** [comment]
Thanks :D. Now that the related PR has been merged to develop, should I close the issue or should I close it once it has been officially released?

**Comment by tokejepsen** [comment]
Let's close it.
