### ISSUE TITLE
Bug: transcode color spaces deleting unprocessed representations

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#6255]
`Transcode color spaces` plugin (`extract_color_transcode.py` or **Extract OIIO Transcode** in the Settings) delete representation triggers for any representation matching its conditions even when it is not processed by it (no transcoding is happening).

**Comment by BigRoy** [comment]
> `_repre_is_valid()` is returning True/False so this condition will not trigger for False values.

Sorry, what?

I don't really understand what you're saying. It returning False or True is perfectly fine - right?

**Comment by BigRoy** [comment]
> expecting return value `None` is getting `bool`

Why do you feel like it's expecting a `None` value? The python `if` and `if not` works perfectly fine for booleans.

**Comment by antirotor** [comment]
> > `_repre_is_valid()` is returning True/False so this condition will not trigger for False values.
> 
> Sorry, what?
> 
> I don't really understand what you're saying. It returning False or True is perfectly fine - right?
> 
> > expecting return value `None` is getting `bool`
> 
> Why do you feel like it's expecting a `None` value? The python `if` and `if not` works perfectly fine for booleans.

Right, morning fatigue. It is actually happening because of wrong nesting of loops. `_repre_is_valid()` will skip the processing in first loop, but not in the next that is removing representations.

**Comment by dee-ynput** [comment]
closing: won't do - fixed in AYON (https://github.com/ynput/ayon-core/issues/275)
