### ISSUE TITLE
houdini: colorspaces

### ISSUE THREAD

**Issue by mkolar** [ynput/OpenPype#67]
<p>Implement houdini color management to get on par with Nuke.</p>
<i>[PYPE-78] created by jakub</i>

[cuID:[OP-1017](https://app.clickup.com/t/yjx79x)]

**Comment by BigRoy** [comment]
@MustafaJafar how relevant is this still in AYON? Can we close it or should we transfer to `ayon-houdini`?

**Comment by MustafaJafar** [comment]
The associated internal ticket was closed, closing therefore closing this one.
