### ISSUE TITLE
Build Workfile: Create instances

### ISSUE THREAD

**Issue by tokejepsen** [ynput/OpenPype#838]
**Goal**

Create studio specific instances when building a workfile.

**Motivation**

When users build a workfile they will need to create instances as well before being able to publish. These instances are often standardized on a project, for example animation will always wanna create a review instance.

**Implementation**

Running the creator plugins would happen after all loading has been done.

Which creator plugins to run and input settings to the creator plugins would be studio specific.

[cuID:[OP-1048](https://app.clickup.com/t/yjx8xe)]

**Comment by tokejepsen** [comment]
@iLLiCiTiT suggested to separate the loading and creating.

Guessing this means to separate the code part of loading and creating?

**Comment by mkolar** [comment]
I think that the scene build should ultimately take care of both, but in the code they need to be separate, so it's possible to run only one or the other if need be.

**Comment by mkolar** [comment]
I made a miro board for scheming over this. For edit permission ask for a password, we'll make it publicly viewable as well.

https://miro.com/app/board/o9J_lazDzXA=/

**Comment by mkolar** [comment]
This in unfortunatelly stuck in limbo due lack of time to fully implement the new publisher GUI. That work includes programable creators and paves road for this.

**Comment by tokejepsen** [comment]
Would the template workfile builder be able to take care of this?
Haven't looked at that code yet but you could have the instances already created there.

**Comment by mkolar** [comment]
this has been resolved with template building. closing
